// HL7 Message - FHIR R4_ ADT_A01 - Sheet1.csv
Instance: MessageADT_A01toBundle
InstanceOf: ConceptMap
Title: "Message ADT_A01 to Bundle Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Message ADT_A01 to the FHIR Message Bundle."
* id = "message-adt-a01-to-bundle"
* url = "http://hl7.org/fhir/v2-tofhir/message-adt-a01-to-bundle"
* version = "1.0"
* name = "MessageADT_A01toBundle"
* status = #active
* experimental = true
* date = "2020-08-11"
* publisher = "HL7 International, Inc"
* contact.telecom.system = #email
* contact.telecom.value = "v2-to-fhir@lists.hl7.org"
* copyright = "Copyright (c) 2020, HL7 International, Inc., All Rights Reserved."
* sourceUri = "ADT_A01"
* targetUri = "Bundle"
* extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Message ADT:A01 to Bundle.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1kPOewgrlY4Mpi8W3HyLzb5J-tuZnUBAzgsXuhX5lcGo/edit#gid=0"
* group.element[0].code = #ADT_A01.MSH
* group.element[0].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[0].extension[0].extension[0].url = "cardinalityMin"
* group.element[0].extension[0].extension[0].valueInteger = 1
* group.element[0].extension[0].extension[1].url = "cardinalityMax"
* group.element[0].extension[0].extension[1].valueInteger = 1
* group.element[0].display = "Message Header"
* group.element[0].target.equivalence = #equivalent
* group.element[0].target.code = #Bundle
* group.element[0].target.display = "Bundle"
* group.element[0].target.dependsOn[0].property = "segment-map"
* group.element[0].target.dependsOn[0].value = "MSH[Bundle]"
* group.element[1].code = #ADT_A01.MSH
* group.element[1].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[1].extension[0].extension[0].url = "cardinalityMin"
* group.element[1].extension[0].extension[0].valueInteger = 1
* group.element[1].extension[0].extension[1].url = "cardinalityMax"
* group.element[1].extension[0].extension[1].valueInteger = 1
* group.element[1].display = "Message Header"
* group.element[1].target.equivalence = #equivalent
* group.element[1].target.code = #MessageHeader[1]
* group.element[1].target.display = "MessageHeader[1]"
* group.element[1].target.comment = "Processing of the MSH segment results in the creation of a new MessageHeader resource"
* group.element[1].target.dependsOn[0].property = "segment-map"
* group.element[1].target.dependsOn[0].value = "MSH[MessageHeader]"
* group.element[2].code = #ADT_A01.MSH
* group.element[2].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[2].extension[0].extension[0].url = "cardinalityMin"
* group.element[2].extension[0].extension[0].valueInteger = 1
* group.element[2].extension[0].extension[1].url = "cardinalityMax"
* group.element[2].extension[0].extension[1].valueInteger = 1
* group.element[2].display = "Message Header"
* group.element[2].target.equivalence = #equivalent
* group.element[2].target.code = #Provenance[1]
* group.element[2].target.display = "Provenance[1]"
* group.element[2].target.dependsOn[0].property = "segment-map"
* group.element[2].target.dependsOn[0].value = "MSH[Provenance]"
* group.element[2].target.dependsOn[1].property = "references"
* group.element[2].target.dependsOn[1].value = "Provenance.target=Bundle; Provenance.target=MessageHeader[MSH]"
* group.element[3].code = #ADT_A01.SFT
* group.element[3].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[3].extension[0].extension[0].url = "cardinalityMin"
* group.element[3].extension[0].extension[0].valueInteger = 0
* group.element[3].extension[0].extension[1].url = "cardinalityMax"
* group.element[3].extension[0].extension[1].valueInteger = -1
* group.element[3].display = "Software Segment"
* group.element[3].target.equivalence = #equivalent
* group.element[3].target.code = #MessageHeader[1]
* group.element[3].target.display = "MessageHeader[1]"
* group.element[3].target.comment = "Incorporate SFT content for each of the SFT instances into the MessageHeader created from the MSH segment."
* group.element[3].target.dependsOn[0].property = "segment-map"
* group.element[3].target.dependsOn[0].value = "SFT[MessageHeader]"
* group.element[4].code = #ADT_A01.EVN
* group.element[4].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[4].extension[0].extension[0].url = "cardinalityMin"
* group.element[4].extension[0].extension[0].valueInteger = 1
* group.element[4].extension[0].extension[1].url = "cardinalityMax"
* group.element[4].extension[0].extension[1].valueInteger = 1
* group.element[4].display = "Event Type"
* group.element[4].target.equivalence = #equivalent
* group.element[4].target.code = #Provenance[2]
* group.element[4].target.display = "Provenance[2]"
* group.element[4].target.dependsOn[0].property = "segment-map"
* group.element[4].target.dependsOn[0].value = "EVN[Provenance]"
* group.element[4].target.dependsOn[1].property = "references"
* group.element[4].target.dependsOn[1].value = "Provenance.target=Bundle; Provenance.target=MessageHeader"
* group.element[5].code = #ADT_A01.PID
* group.element[5].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[5].extension[0].extension[0].url = "cardinalityMin"
* group.element[5].extension[0].extension[0].valueInteger = 1
* group.element[5].extension[0].extension[1].url = "cardinalityMax"
* group.element[5].extension[0].extension[1].valueInteger = 1
* group.element[5].display = "Patient Identification"
* group.element[5].target.equivalence = #equivalent
* group.element[5].target.code = #Patient[1]
* group.element[5].target.display = "Patient[1]"
* group.element[5].target.comment = "Processing of the PID segment results in the creation of a new Patient resource"
* group.element[5].target.dependsOn[0].property = "segment-map"
* group.element[5].target.dependsOn[0].value = "PID[Patient]"
* group.element[6].code = #ADT_A01.PID
* group.element[6].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[6].extension[0].extension[0].url = "cardinalityMin"
* group.element[6].extension[0].extension[0].valueInteger = 1
* group.element[6].extension[0].extension[1].url = "cardinalityMax"
* group.element[6].extension[0].extension[1].valueInteger = 1
* group.element[6].display = "Patient Identification"
* group.element[6].target.equivalence = #equivalent
* group.element[6].target.code = #Observation[1]
* group.element[6].target.display = "Observation[1]"
* group.element[6].target.dependsOn[0].property = "segment-map"
* group.element[6].target.dependsOn[0].value = "PID[Observation-Race]"
* group.element[6].target.dependsOn[1].property = "references"
* group.element[6].target.dependsOn[1].value = "Observation.subject.reference=Patient[1].id"
* group.element[6].target.product[0].property = "narrative"
* group.element[6].target.product[0].value = "If PID-10 is for clinical purposes"
* group.element[7].code = #ADT_A01.PID
* group.element[7].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[7].extension[0].extension[0].url = "cardinalityMin"
* group.element[7].extension[0].extension[0].valueInteger = 1
* group.element[7].extension[0].extension[1].url = "cardinalityMax"
* group.element[7].extension[0].extension[1].valueInteger = 1
* group.element[7].display = "Patient Identification"
* group.element[7].target.equivalence = #equivalent
* group.element[7].target.code = #Observation[2]
* group.element[7].target.display = "Observation[2]"
* group.element[7].target.dependsOn[0].property = "segment-map"
* group.element[7].target.dependsOn[0].value = "PID[Observation-EthnicGroup]"
* group.element[7].target.dependsOn[1].property = "references"
* group.element[7].target.dependsOn[1].value = "Obsevation.subject.reference=Patient[1].id"
* group.element[7].target.product[0].property = "narrative"
* group.element[7].target.product[0].value = "IF PID-22 is for clinical purposes"
* group.element[8].code = #ADT_A01.PID
* group.element[8].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[8].extension[0].extension[0].url = "cardinalityMin"
* group.element[8].extension[0].extension[0].valueInteger = 1
* group.element[8].extension[0].extension[1].url = "cardinalityMax"
* group.element[8].extension[0].extension[1].valueInteger = 1
* group.element[8].display = "Patient Identification"
* group.element[8].target.equivalence = #equivalent
* group.element[8].target.code = #RelatedPerson
* group.element[8].target.display = "RelatedPerson"
* group.element[8].target.dependsOn[0].property = "segment-map"
* group.element[8].target.dependsOn[0].value = "PID[RelatedPerson-Mother]"
* group.element[8].target.dependsOn[1].property = "references"
* group.element[8].target.dependsOn[1].value = "RelatedPerson.patient.reference=Patient[1].id"
* group.element[9].code = #ADT_A01.PID
* group.element[9].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[9].extension[0].extension[0].url = "cardinalityMin"
* group.element[9].extension[0].extension[0].valueInteger = 1
* group.element[9].extension[0].extension[1].url = "cardinalityMax"
* group.element[9].extension[0].extension[1].valueInteger = 1
* group.element[9].display = "Patient Identification"
* group.element[9].target.equivalence = #equivalent
* group.element[9].target.code = #Account
* group.element[9].target.display = "Account"
* group.element[9].target.dependsOn[0].property = "segment-map"
* group.element[9].target.dependsOn[0].value = "PID[Account]"
* group.element[9].target.dependsOn[1].property = "references"
* group.element[9].target.dependsOn[1].value = "Account.subject.reference=Patient[1].id"
* group.element[10].code = #ADT_A01.PD1
* group.element[10].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[10].extension[0].extension[0].url = "cardinalityMin"
* group.element[10].extension[0].extension[0].valueInteger = 0
* group.element[10].extension[0].extension[1].url = "cardinalityMax"
* group.element[10].extension[0].extension[1].valueInteger = 1
* group.element[10].display = "Additional Demographics"
* group.element[10].target.equivalence = #equivalent
* group.element[10].target.code = #Patient[1]
* group.element[10].target.display = "Patient[1]"
* group.element[10].target.comment = "Incorporate PD1 content into the Patient created from the PID segment."
* group.element[10].target.dependsOn[0].property = "segment-map"
* group.element[10].target.dependsOn[0].value = "PD1[Patient]"
* group.element[11].code = #ADT_A01:follow:PID.ARV
* group.element[11].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[11].extension[0].extension[0].url = "cardinalityMin"
* group.element[11].extension[0].extension[0].valueInteger = 0
* group.element[11].extension[0].extension[1].url = "cardinalityMax"
* group.element[11].extension[0].extension[1].valueInteger = -1
* group.element[11].display = "Access Restrictions"
* group.element[11].target.equivalence = #equivalent
* group.element[11].target.code = #Patient[1]
* group.element[11].target.display = "Patient[1]"
* group.element[11].target.comment = "FHIR does not yet support field level security tags.  The ARV, when located with the PID/PD1 in the v2 message, is meant to only apply to the patient.  However, technically it could point to other places in the messageas as well.  That is considered out of scope as."
* group.element[11].target.dependsOn[0].property = "segment-map"
* group.element[11].target.dependsOn[0].value = "ARV[Patient]"
* group.element[11].target.dependsOn[1].property = "references"
* group.element[11].target.dependsOn[1].value = "Resource=Patient[1]"
* group.element[11].target.product[0].property = "antlr"
* group.element[11].target.product[0].value = "IF ARV-1 IN (\"PID\", \"PD1\") AND ARV-3 NOT VALUED"
* group.element[12].code = #ADT_A01:follow:PID.ROL
* group.element[12].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[12].extension[0].extension[0].url = "cardinalityMin"
* group.element[12].extension[0].extension[0].valueInteger = 0
* group.element[12].extension[0].extension[1].url = "cardinalityMax"
* group.element[12].extension[0].extension[1].valueInteger = -1
* group.element[12].display = "Role"
* group.element[12].target.equivalence = #equivalent
* group.element[12].target.code = #Patient[1]
* group.element[12].target.display = "Patient[1]"
* group.element[12].target.dependsOn[0].property = "segment-map"
* group.element[12].target.dependsOn[0].value = "ROL[Patient-PractitionerRole]"
* group.element[12].target.product[0].property = "antlr"
* group.element[12].target.product[0].value = "IF ROL-3.1 EQUALS \"PP\" AND ROL-3.3 EQUALS \"HL70443\""
* group.element[12].target.product[1].property = "fhirpath"
* group.element[12].target.product[1].value = "(element(\"3.1\")=\"PP\")and(element(\"3.3\")=\"HL70443\")"
* group.element[13].code = #ADT_A01:follow:PID.ROL
* group.element[13].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[13].extension[0].extension[0].url = "cardinalityMin"
* group.element[13].extension[0].extension[0].valueInteger = 0
* group.element[13].extension[0].extension[1].url = "cardinalityMax"
* group.element[13].extension[0].extension[1].valueInteger = -1
* group.element[13].display = "Role"
* group.element[13].target.equivalence = #equivalent
* group.element[13].target.code = #RelatedPerson[1]
* group.element[13].target.display = "RelatedPerson[1]"
* group.element[13].target.dependsOn[0].property = "segment-map"
* group.element[13].target.dependsOn[0].value = "ROL[RelatedPerson]"
* group.element[13].target.dependsOn[1].property = "references"
* group.element[13].target.dependsOn[1].value = "RelatedPerson[1].patient.reference=Patient[1].id"
* group.element[13].target.product[0].property = "antlr"
* group.element[13].target.product[0].value = "IF ROL-3.1 NOT EQUALS  \"PP\" OR ROL-3.3 NOT EQUALS \"HL70443\""
* group.element[13].target.product[1].property = "fhirpath"
* group.element[13].target.product[1].value = "(element(\"3.1\")!=\"PP\")or(element(\"3.3\")!=\"HL70443\")"
* group.element[13].target.product[2].property = "narrative"
* group.element[13].target.product[2].value = "While most likely all other HL70443 values go to RelatedPerson, the implementation needs to determine whether that is fully accurate."
* group.element[14].code = #ADT_A01.NK1
* group.element[14].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[14].extension[0].extension[0].url = "cardinalityMin"
* group.element[14].extension[0].extension[0].valueInteger = 0
* group.element[14].extension[0].extension[1].url = "cardinalityMax"
* group.element[14].extension[0].extension[1].valueInteger = -1
* group.element[14].display = "Next of Kin / Associated Parties"
* group.element[14].target.equivalence = #equivalent
* group.element[14].target.code = #RelatedPerson[2]
* group.element[14].target.display = "RelatedPerson[2]"
* group.element[14].target.comment = "Typically, each NK1 will be translated to either a new RelatedPerson resource or added as a new occurrence of Patient.contact, but it's possible to insert the NK1 data into both structures."
* group.element[14].target.dependsOn[0].property = "segment-map"
* group.element[14].target.dependsOn[0].value = "NK1[RelatedPerson]"
* group.element[14].target.dependsOn[1].property = "references"
* group.element[14].target.dependsOn[1].value = "RelatedPerson[2].patient.reference=Patient[1].id"
* group.element[14].target.product[0].property = "antlr"
* group.element[14].target.product[0].value = "IF NK1-3.1 NOT IN (\"EMR\", \"E\", \"F\", \"I\", \"S\")"
* group.element[15].code = #ADT_A01.NK1
* group.element[15].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[15].extension[0].extension[0].url = "cardinalityMin"
* group.element[15].extension[0].extension[0].valueInteger = 0
* group.element[15].extension[0].extension[1].url = "cardinalityMax"
* group.element[15].extension[0].extension[1].valueInteger = -1
* group.element[15].display = "Next of Kin / Associated Parties"
* group.element[15].target.equivalence = #equivalent
* group.element[15].target.code = #Patient[1]
* group.element[15].target.display = "Patient[1]"
* group.element[15].target.dependsOn[0].property = "segment-map"
* group.element[15].target.dependsOn[0].value = "NK1[Patient]"
* group.element[15].target.product[0].property = "antlr"
* group.element[15].target.product[0].value = "IF NK1-3.1 NOT IN (\"EMR\", \"E\", \"F\", \"I\", \"S\")"
* group.element[16].code = #ADT_A01.NK1
* group.element[16].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[16].extension[0].extension[0].url = "cardinalityMin"
* group.element[16].extension[0].extension[0].valueInteger = 0
* group.element[16].extension[0].extension[1].url = "cardinalityMax"
* group.element[16].extension[0].extension[1].valueInteger = -1
* group.element[16].display = "Next of Kin / Associated Parties"
* group.element[16].target.equivalence = #equivalent
* group.element[16].target.code = #Patient[1]
* group.element[16].target.display = "Patient[1]"
* group.element[16].target.dependsOn[0].property = "segment-map"
* group.element[16].target.dependsOn[0].value = "NK1[Patient]"
* group.element[16].target.product[0].property = "antlr"
* group.element[16].target.product[0].value = "IF NK1-3.1 IN (\"EMR\", \"E\", \"F\", \"I\", \"S\")"
* group.element[17].code = #ADT_A01.PV1
* group.element[17].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[17].extension[0].extension[0].url = "cardinalityMin"
* group.element[17].extension[0].extension[0].valueInteger = 1
* group.element[17].extension[0].extension[1].url = "cardinalityMax"
* group.element[17].extension[0].extension[1].valueInteger = 1
* group.element[17].display = "Patient Visit"
* group.element[17].target.equivalence = #equivalent
* group.element[17].target.code = #Encounter[1]
* group.element[17].target.display = "Encounter[1]"
* group.element[17].target.comment = "Processing of the PV1 segment results in the creation of a new Encounter resource"
* group.element[17].target.dependsOn[0].property = "segment-map"
* group.element[17].target.dependsOn[0].value = "PV1[Encounter]"
* group.element[17].target.dependsOn[1].property = "references"
* group.element[17].target.dependsOn[1].value = "Encounter[1].subject.reference=Patient[1].id"
* group.element[18].code = #ADT_A01.PV1
* group.element[18].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[18].extension[0].extension[0].url = "cardinalityMin"
* group.element[18].extension[0].extension[0].valueInteger = 1
* group.element[18].extension[0].extension[1].url = "cardinalityMax"
* group.element[18].extension[0].extension[1].valueInteger = 1
* group.element[18].display = "Patient Visit"
* group.element[18].target.equivalence = #equivalent
* group.element[18].target.code = #Patient[1]
* group.element[18].target.display = "Patient[1]"
* group.element[18].target.dependsOn[0].property = "segment-map"
* group.element[18].target.dependsOn[0].value = "PV1[Patient]"
* group.element[19].code = #ADT_A01.PV2
* group.element[19].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[19].extension[0].extension[0].url = "cardinalityMin"
* group.element[19].extension[0].extension[0].valueInteger = 0
* group.element[19].extension[0].extension[1].url = "cardinalityMax"
* group.element[19].extension[0].extension[1].valueInteger = 1
* group.element[19].display = "Patient Visit - Additional Info."
* group.element[19].target.equivalence = #equivalent
* group.element[19].target.code = #Encounter[1]
* group.element[19].target.display = "Encounter[1]"
* group.element[19].target.comment = "Incorporate PV2 content into the Encounter created from the PV1 segment."
* group.element[19].target.dependsOn[0].property = "segment-map"
* group.element[19].target.dependsOn[0].value = "PV2[Encounter]"
* group.element[20].code = #ADT_A01:follow:PV1.ARV
* group.element[20].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[20].extension[0].extension[0].url = "cardinalityMin"
* group.element[20].extension[0].extension[0].valueInteger = 0
* group.element[20].extension[0].extension[1].url = "cardinalityMax"
* group.element[20].extension[0].extension[1].valueInteger = -1
* group.element[20].display = "Access Restrictions"
* group.element[20].target.equivalence = #equivalent
* group.element[20].target.code = #Encounter[1]
* group.element[20].target.display = "Encounter[1]"
* group.element[20].target.comment = "FHIR does not yet support field level security tags.  The ARV, when located with the PV1/PV2 in the v2 message, is meant to only apply to the encounter.  However, technically it could point to other places in the messageas as well.  That is considered out of scope as."
* group.element[20].target.dependsOn[0].property = "segment-map"
* group.element[20].target.dependsOn[0].value = "ARV[Encounter]"
* group.element[20].target.dependsOn[1].property = "references"
* group.element[20].target.dependsOn[1].value = "Resource=Encounter[1]"
* group.element[20].target.product[0].property = "antlr"
* group.element[20].target.product[0].value = "IF  ARV-3 NOT VALUED"
* group.element[21].code = #ADT_A01:follow:PV1.ROL
* group.element[21].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[21].extension[0].extension[0].url = "cardinalityMin"
* group.element[21].extension[0].extension[0].valueInteger = 0
* group.element[21].extension[0].extension[1].url = "cardinalityMax"
* group.element[21].extension[0].extension[1].valueInteger = -1
* group.element[21].display = "Role"
* group.element[21].target.equivalence = #equivalent
* group.element[21].target.code = #Encounter[1]
* group.element[21].target.display = "Encounter[1]"
* group.element[21].target.dependsOn[0].property = "segment-map"
* group.element[21].target.dependsOn[0].value = "ROL[Encounter-PractitionerRole]"
* group.element[22].code = #ADT_A01.OBX
* group.element[22].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[22].extension[0].extension[0].url = "cardinalityMin"
* group.element[22].extension[0].extension[0].valueInteger = 0
* group.element[22].extension[0].extension[1].url = "cardinalityMax"
* group.element[22].extension[0].extension[1].valueInteger = -1
* group.element[22].display = "Observation/Result"
* group.element[22].target.equivalence = #equivalent
* group.element[22].target.code = #Observation[2]
* group.element[22].target.display = "Observation[2]"
* group.element[22].target.dependsOn[0].property = "segment-map"
* group.element[22].target.dependsOn[0].value = "OBX[Observation]"
* group.element[22].target.dependsOn[1].property = "references"
* group.element[22].target.dependsOn[1].value = "Observation.subject.reference=Patient[1].id; Observation.encounter.reference=Encounter[1].id"
* group.element[22].target.product[0].property = "narrative"
* group.element[22].target.product[0].value = "Based on profiles, such as Vital Signs, certain observations are represented on the Observation, while others on its components.  No computable guidance available yet."
* group.element[23].code = #ADT_A01.OBX
* group.element[23].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[23].extension[0].extension[0].url = "cardinalityMin"
* group.element[23].extension[0].extension[0].valueInteger = 0
* group.element[23].extension[0].extension[1].url = "cardinalityMax"
* group.element[23].extension[0].extension[1].valueInteger = -1
* group.element[23].display = "Observation/Result"
* group.element[23].target.equivalence = #equivalent
* group.element[23].target.code = #Observation[2]
* group.element[23].target.display = "Observation[2]"
* group.element[23].target.dependsOn[0].property = "segment-map"
* group.element[23].target.dependsOn[0].value = "OBX[Observation-Component]"
* group.element[23].target.dependsOn[1].property = "references"
* group.element[23].target.dependsOn[1].value = "Observation.subject.reference=Patient[1].id; Observation.encounter.reference=Encounter[1].id"
* group.element[23].target.product[0].property = "narrative"
* group.element[23].target.product[0].value = "Based on profiles, such as Vital Signs, certain observations are represented on the Observation, while others on its components.  No computable guidance available yet."
* group.element[24].code = #ADT_A01.AL1
* group.element[24].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[24].extension[0].extension[0].url = "cardinalityMin"
* group.element[24].extension[0].extension[0].valueInteger = 0
* group.element[24].extension[0].extension[1].url = "cardinalityMax"
* group.element[24].extension[0].extension[1].valueInteger = -1
* group.element[24].display = "Allergy Information"
* group.element[24].target.equivalence = #equivalent
* group.element[24].target.code = #AllergyIntolerance
* group.element[24].target.display = "AllergyIntolerance"
* group.element[24].target.comment = "Processing of the AL1 segment results in the creation of a new AllergyIntolerance resource"
* group.element[24].target.dependsOn[0].property = "segment-map"
* group.element[24].target.dependsOn[0].value = "AL1[AllergyIntolerance]"
* group.element[24].target.dependsOn[1].property = "references"
* group.element[24].target.dependsOn[1].value = "AllergyIntolerance.patient.reference=Patient[1].id"
* group.element[25].code = #ADT_A01.DG1
* group.element[25].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[25].extension[0].extension[0].url = "cardinalityMin"
* group.element[25].extension[0].extension[0].valueInteger = 0
* group.element[25].extension[0].extension[1].url = "cardinalityMax"
* group.element[25].extension[0].extension[1].valueInteger = -1
* group.element[25].display = "Diagnosis Information"
* group.element[25].target.equivalence = #equivalent
* group.element[25].target.code = #Condition
* group.element[25].target.display = "Condition"
* group.element[25].target.comment = "Processing of the DG1 segment results in the creation of a new Condition resource"
* group.element[25].target.dependsOn[0].property = "segment-map"
* group.element[25].target.dependsOn[0].value = "DG1[Condition]"
* group.element[25].target.dependsOn[1].property = "references"
* group.element[25].target.dependsOn[1].value = "Condition.subject.reference=Patient[1].id"
* group.element[25].target.product[0].property = "narrative"
* group.element[25].target.product[0].value = "If in context of the patient"
* group.element[26].code = #ADT_A01.DG1
* group.element[26].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[26].extension[0].extension[0].url = "cardinalityMin"
* group.element[26].extension[0].extension[0].valueInteger = 0
* group.element[26].extension[0].extension[1].url = "cardinalityMax"
* group.element[26].extension[0].extension[1].valueInteger = -1
* group.element[26].display = "Diagnosis Information"
* group.element[26].target.equivalence = #equivalent
* group.element[26].target.code = #Encounter[1]
* group.element[26].target.display = "Encounter[1]"
* group.element[26].target.dependsOn[0].property = "segment-map"
* group.element[26].target.dependsOn[0].value = "DG1[Encounter]"
* group.element[26].target.dependsOn[1].property = "references"
* group.element[26].target.dependsOn[1].value = "Encounter[1].diagnosis.reference=Condition[1].id"
* group.element[26].target.product[0].property = "narrative"
* group.element[26].target.product[0].value = "If in context of an encounter"
* group.element[27].code = #ADT_A01.DG1
* group.element[27].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[27].extension[0].extension[0].url = "cardinalityMin"
* group.element[27].extension[0].extension[0].valueInteger = 0
* group.element[27].extension[0].extension[1].url = "cardinalityMax"
* group.element[27].extension[0].extension[1].valueInteger = -1
* group.element[27].display = "Diagnosis Information"
* group.element[27].target.equivalence = #equivalent
* group.element[27].target.code = #EpisodeOfCare[1]
* group.element[27].target.display = "EpisodeOfCare[1]"
* group.element[27].target.dependsOn[0].property = "segment-map"
* group.element[27].target.dependsOn[0].value = "DG1[EpisodeOfCare]"
* group.element[27].target.dependsOn[1].property = "references"
* group.element[27].target.dependsOn[1].value = "EpisodeOfCare.diagnosis.reference=Condition[1].id"
* group.element[27].target.product[0].property = "narrative"
* group.element[27].target.product[0].value = "If in context of a episode of care"
* group.element[28].code = #ADT_A01.PROCEDURE.PR1
* group.element[28].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[28].extension[0].extension[0].url = "cardinalityMin"
* group.element[28].extension[0].extension[0].valueInteger = 1
* group.element[28].extension[0].extension[1].url = "cardinalityMax"
* group.element[28].extension[0].extension[1].valueInteger = 1
* group.element[28].display = "Procedures"
* group.element[28].target.equivalence = #equivalent
* group.element[28].target.code = #Procedure
* group.element[28].target.display = "Procedure"
* group.element[28].target.dependsOn[0].property = "segment-map"
* group.element[28].target.dependsOn[0].value = "PR1[Procedure]"
* group.element[28].target.dependsOn[1].property = "references"
* group.element[28].target.dependsOn[1].value = "Procedure.subject.reference=Patient[1].id"
* group.element[29].code = #ADT_A01.INSURANCE.IN1
* group.element[29].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[29].extension[0].extension[0].url = "cardinalityMin"
* group.element[29].extension[0].extension[0].valueInteger = 1
* group.element[29].extension[0].extension[1].url = "cardinalityMax"
* group.element[29].extension[0].extension[1].valueInteger = 1
* group.element[29].display = "Insurance"
* group.element[29].target.equivalence = #equivalent
* group.element[29].target.code = #Coverage[1]
* group.element[29].target.display = "Coverage[1]"
* group.element[29].target.comment = "Processing of the IN1 segment results in the creation of a new Coverage resource"
* group.element[29].target.dependsOn[0].property = "segment-map"
* group.element[29].target.dependsOn[0].value = "IN1[Coverage]"
* group.element[29].target.dependsOn[1].property = "references"
* group.element[29].target.dependsOn[1].value = "Coverage.subscriber.reference=Patient[1].id"
* group.element[30].code = #ADT_A01.INSURANCE.IN2
* group.element[30].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[30].extension[0].extension[0].url = "cardinalityMin"
* group.element[30].extension[0].extension[0].valueInteger = 0
* group.element[30].extension[0].extension[1].url = "cardinalityMax"
* group.element[30].extension[0].extension[1].valueInteger = 1
* group.element[30].display = "Insurance Additional Info."
* group.element[30].target.equivalence = #equivalent
* group.element[30].target.code = #Coverage[1]
* group.element[30].target.display = "Coverage[1]"
* group.element[30].target.comment = "Incorporate IN2 content into the Coverage created from the IN1 segment."
* group.element[30].target.dependsOn[0].property = "segment-map"
* group.element[30].target.dependsOn[0].value = "IN2[Coverage]"
* group.element[31].code = #ADT_A01.INSURANCE.IN3
* group.element[31].extension[0].url = "http://hl7.org/fhir/v2-tofhir/StructureDefinition/TypeInfo"
* group.element[31].extension[0].extension[0].url = "cardinalityMin"
* group.element[31].extension[0].extension[0].valueInteger = 0
* group.element[31].extension[0].extension[1].url = "cardinalityMax"
* group.element[31].extension[0].extension[1].valueInteger = -1
* group.element[31].display = "Insurance Additional Info - Cert."
* group.element[31].target.equivalence = #equivalent
* group.element[31].target.code = #Coverage[1]
* group.element[31].target.display = "Coverage[1]"
* group.element[31].target.comment = "Incorporate IN3 content into the Coverage created from the IN1 segment."
* group.element[31].target.dependsOn[0].property = "segment-map"
* group.element[31].target.dependsOn[0].value = "IN3[Coverage]"
