// HL7 Data Type - FHIR R4_ CWE[Device] - Sheet1.csv
Instance: DatatypeCWEToDevice
InstanceOf: ConceptMap
Title: "Datatype CWE to Device Map"
Usage: #definition
* title = "Datatype CWE to Device Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Datatype CWE to the FHIR Device Resource."
* id = "datatype-cwe-to-device"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/datatype-cwe-to-device"
* name = "DatatypeCWEToDevice"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Datatype CWE to Device.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/13LJngzZ_t2CzddzgZu8MR1dbNJfyH9mWN1cRzRs7VIQ/edit#gid=0"
* group[0].element[0].code = #CWE.1
* group[0].element[0].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[0].extension[0].extension[0].url = "type"
* group[0].element[0].extension[0].extension[0].valueCode = #"ST"
* group[0].element[0].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[0].extension[0].extension[1].valueInteger = 0
* group[0].element[0].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[0].extension[0].extension[2].valueInteger = 1
* group[0].element[0].display = "Identifier"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #identifier[1].value
* group[0].element[0].target.display = "identifier[1].value"
* group[0].element[0].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[0].target.dependsOn[0].value = "If instance identifier"
* group[0].element[1].code = #CWE.1
* group[0].element[1].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[1].extension[0].extension[0].url = "type"
* group[0].element[1].extension[0].extension[0].valueCode = #"ST"
* group[0].element[1].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[1].extension[0].extension[1].valueInteger = 0
* group[0].element[1].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[1].extension[0].extension[2].valueInteger = 1
* group[0].element[1].display = "Identifier"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #definition(DeviceDefinition.identifier[1].value)
* group[0].element[1].target.display = "definition(DeviceDefinition.identifier[1].value)"
* group[0].element[1].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[1].target.dependsOn[0].value = "If kind identifier"
* group[0].element[2].code = #CWE.2
* group[0].element[2].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[2].extension[0].extension[0].url = "type"
* group[0].element[2].extension[0].extension[0].valueCode = #"ST"
* group[0].element[2].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[2].extension[0].extension[1].valueInteger = 0
* group[0].element[2].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[2].extension[0].extension[2].valueInteger = 1
* group[0].element[2].display = "Text"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #deviceName[1].name
* group[0].element[2].target.display = "deviceName[1].name"
* group[0].element[3].code = #CWE.2
* group[0].element[3].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].extension[0].extension[0].url = "type"
* group[0].element[3].extension[0].extension[0].valueCode = #"ST"
* group[0].element[3].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[3].extension[0].extension[1].valueInteger = 0
* group[0].element[3].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[3].extension[0].extension[2].valueInteger = 1
* group[0].element[3].display = "Text"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #deviceName[1].type
* group[0].element[3].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].target.extension[0].extension[0].url = "assignment"
* group[0].element[3].target.extension[0].extension[0].valueString = "/select most appropriate value for actual use/"
* group[0].element[3].target.display = "deviceName[1].type"
* group[0].element[4].code = #CWE.3
* group[0].element[4].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].extension[0].extension[0].url = "type"
* group[0].element[4].extension[0].extension[0].valueCode = #"ID"
* group[0].element[4].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[4].extension[0].extension[1].valueInteger = 0
* group[0].element[4].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[4].extension[0].extension[2].valueInteger = 1
* group[0].element[4].display = "Name of Coding System"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #identifier[1].system
* group[0].element[4].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].target.extension[0].extension[0].url = "assignment"
* group[0].element[4].target.extension[0].extension[0].valueString = "/map HL7 code system to appropriate url/"
* group[0].element[4].target.display = "identifier[1].system"
* group[0].element[4].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[4].target.dependsOn[0].value = "If instance identifier"
* group[0].element[5].code = #CWE.3
* group[0].element[5].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[5].extension[0].extension[0].url = "type"
* group[0].element[5].extension[0].extension[0].valueCode = #"ID"
* group[0].element[5].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[5].extension[0].extension[1].valueInteger = 0
* group[0].element[5].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[5].extension[0].extension[2].valueInteger = 1
* group[0].element[5].display = "Name of Coding System"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #definition(DeviceDefinition.identifier[1].system)
* group[0].element[5].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[5].target.extension[0].extension[0].url = "assignment"
* group[0].element[5].target.extension[0].extension[0].valueString = "/map HL7 code system to appropriate url/"
* group[0].element[5].target.display = "definition(DeviceDefinition.identifier[1].system)"
* group[0].element[5].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[5].target.dependsOn[0].value = "If kind identifier"
* group[0].element[6].code = #CWE.4
* group[0].element[6].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[6].extension[0].extension[0].url = "type"
* group[0].element[6].extension[0].extension[0].valueCode = #"ST"
* group[0].element[6].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[6].extension[0].extension[1].valueInteger = 0
* group[0].element[6].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[6].extension[0].extension[2].valueInteger = 1
* group[0].element[6].display = "Alternate Identifier"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #identifier[2].value
* group[0].element[6].target.display = "identifier[2].value"
* group[0].element[6].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[6].target.dependsOn[0].value = "If instance identifier"
* group[0].element[7].code = #CWE.4
* group[0].element[7].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[7].extension[0].extension[0].url = "type"
* group[0].element[7].extension[0].extension[0].valueCode = #"ST"
* group[0].element[7].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[7].extension[0].extension[1].valueInteger = 0
* group[0].element[7].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[7].extension[0].extension[2].valueInteger = 1
* group[0].element[7].display = "Alternate Identifier"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #definition(DeviceDefinition.identifier[2].value)
* group[0].element[7].target.display = "definition(DeviceDefinition.identifier[2].value)"
* group[0].element[7].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[7].target.dependsOn[0].value = "If kind identifier"
* group[0].element[8].code = #CWE.5
* group[0].element[8].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[8].extension[0].extension[0].url = "type"
* group[0].element[8].extension[0].extension[0].valueCode = #"ST"
* group[0].element[8].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[8].extension[0].extension[1].valueInteger = 0
* group[0].element[8].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[8].extension[0].extension[2].valueInteger = 1
* group[0].element[8].display = "Alternate Text"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #deviceName[2].name
* group[0].element[8].target.display = "deviceName[2].name"
* group[0].element[9].code = #CWE.5
* group[0].element[9].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[9].extension[0].extension[0].url = "type"
* group[0].element[9].extension[0].extension[0].valueCode = #"ST"
* group[0].element[9].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[9].extension[0].extension[1].valueInteger = 0
* group[0].element[9].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[9].extension[0].extension[2].valueInteger = 1
* group[0].element[9].display = "Alternate Text"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #deviceName[2].type
* group[0].element[9].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[9].target.extension[0].extension[0].url = "assignment"
* group[0].element[9].target.extension[0].extension[0].valueString = "/select most appropriate value for actual use/"
* group[0].element[9].target.display = "deviceName[2].type"
* group[0].element[10].code = #CWE.6
* group[0].element[10].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[10].extension[0].extension[0].url = "type"
* group[0].element[10].extension[0].extension[0].valueCode = #"ID"
* group[0].element[10].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[10].extension[0].extension[1].valueInteger = 0
* group[0].element[10].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[10].extension[0].extension[2].valueInteger = 1
* group[0].element[10].display = "Name of Alternate Coding System"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #identifier[2].system
* group[0].element[10].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[10].target.extension[0].extension[0].url = "assignment"
* group[0].element[10].target.extension[0].extension[0].valueString = "/map HL7 code system to appropriate url/"
* group[0].element[10].target.display = "identifier[2].system"
* group[0].element[10].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[10].target.dependsOn[0].value = "If instance identifier"
* group[0].element[11].code = #CWE.6
* group[0].element[11].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[11].extension[0].extension[0].url = "type"
* group[0].element[11].extension[0].extension[0].valueCode = #"ID"
* group[0].element[11].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[11].extension[0].extension[1].valueInteger = 0
* group[0].element[11].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[11].extension[0].extension[2].valueInteger = 1
* group[0].element[11].display = "Name of Alternate Coding System"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #definition(DeviceDefinition.identifier[2].system)
* group[0].element[11].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[11].target.extension[0].extension[0].url = "assignment"
* group[0].element[11].target.extension[0].extension[0].valueString = "/map HL7 code system to appropriate url/"
* group[0].element[11].target.display = "definition(DeviceDefinition.identifier[2].system)"
* group[0].element[11].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[11].target.dependsOn[0].value = "If kind identifier"
* group[0].element[12].code = #CWE.9
* group[0].element[12].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[12].extension[0].extension[0].url = "type"
* group[0].element[12].extension[0].extension[0].valueCode = #"ST"
* group[0].element[12].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[12].extension[0].extension[1].valueInteger = 0
* group[0].element[12].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[12].extension[0].extension[2].valueInteger = 1
* group[0].element[12].display = "Original Text"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #deviceName[4].name
* group[0].element[12].target.display = "deviceName[4].name"
* group[0].element[13].code = #CWE.9
* group[0].element[13].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[13].extension[0].extension[0].url = "type"
* group[0].element[13].extension[0].extension[0].valueCode = #"ST"
* group[0].element[13].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[13].extension[0].extension[1].valueInteger = 0
* group[0].element[13].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[13].extension[0].extension[2].valueInteger = 1
* group[0].element[13].display = "Original Text"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #deviceName[4].type
* group[0].element[13].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[13].target.extension[0].extension[0].url = "assignment"
* group[0].element[13].target.extension[0].extension[0].valueString = "/select most appropriate value for actual use/"
* group[0].element[13].target.display = "deviceName[4].type"
* group[0].element[14].code = #CWE.10
* group[0].element[14].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[14].extension[0].extension[0].url = "type"
* group[0].element[14].extension[0].extension[0].valueCode = #"ST"
* group[0].element[14].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[14].extension[0].extension[1].valueInteger = 0
* group[0].element[14].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[14].extension[0].extension[2].valueInteger = 1
* group[0].element[14].display = "Second Alternate Identifier"
* group[0].element[14].target.equivalence = #equivalent
* group[0].element[14].target.code = #identifier[3].value
* group[0].element[14].target.display = "identifier[3].value"
* group[0].element[14].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[14].target.dependsOn[0].value = "If instance identifier"
* group[0].element[15].code = #CWE.10
* group[0].element[15].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[15].extension[0].extension[0].url = "type"
* group[0].element[15].extension[0].extension[0].valueCode = #"ST"
* group[0].element[15].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[15].extension[0].extension[1].valueInteger = 0
* group[0].element[15].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[15].extension[0].extension[2].valueInteger = 1
* group[0].element[15].display = "Second Alternate Identifier"
* group[0].element[15].target.equivalence = #equivalent
* group[0].element[15].target.code = #definition(DeviceDefinition.identifier[3].value)
* group[0].element[15].target.display = "definition(DeviceDefinition.identifier[3].value)"
* group[0].element[15].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[15].target.dependsOn[0].value = "If kind identifier"
* group[0].element[16].code = #CWE.11
* group[0].element[16].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[16].extension[0].extension[0].url = "type"
* group[0].element[16].extension[0].extension[0].valueCode = #"ST"
* group[0].element[16].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[16].extension[0].extension[1].valueInteger = 0
* group[0].element[16].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[16].extension[0].extension[2].valueInteger = 1
* group[0].element[16].display = "Second Alternate Text"
* group[0].element[16].target.equivalence = #equivalent
* group[0].element[16].target.code = #deviceName[3].name
* group[0].element[16].target.display = "deviceName[3].name"
* group[0].element[17].code = #CWE.11
* group[0].element[17].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[17].extension[0].extension[0].url = "type"
* group[0].element[17].extension[0].extension[0].valueCode = #"ST"
* group[0].element[17].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[17].extension[0].extension[1].valueInteger = 0
* group[0].element[17].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[17].extension[0].extension[2].valueInteger = 1
* group[0].element[17].display = "Second Alternate Text"
* group[0].element[17].target.equivalence = #equivalent
* group[0].element[17].target.code = #deviceName[3].type
* group[0].element[17].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[17].target.extension[0].extension[0].url = "assignment"
* group[0].element[17].target.extension[0].extension[0].valueString = "/select most appropriate value for actual use/"
* group[0].element[17].target.display = "deviceName[3].type"
* group[0].element[18].code = #CWE.12
* group[0].element[18].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[18].extension[0].extension[0].url = "type"
* group[0].element[18].extension[0].extension[0].valueCode = #"ID"
* group[0].element[18].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[18].extension[0].extension[1].valueInteger = 0
* group[0].element[18].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[18].extension[0].extension[2].valueInteger = 1
* group[0].element[18].display = "Name of Second Alternate Coding System"
* group[0].element[18].target.equivalence = #equivalent
* group[0].element[18].target.code = #identifier[3].system
* group[0].element[18].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[18].target.extension[0].extension[0].url = "assignment"
* group[0].element[18].target.extension[0].extension[0].valueString = "/map HL7 code system to appropriate url/"
* group[0].element[18].target.display = "identifier[3].system"
* group[0].element[18].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[18].target.dependsOn[0].value = "If instance identifier"
* group[0].element[19].code = #CWE.12
* group[0].element[19].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[19].extension[0].extension[0].url = "type"
* group[0].element[19].extension[0].extension[0].valueCode = #"ID"
* group[0].element[19].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[19].extension[0].extension[1].valueInteger = 0
* group[0].element[19].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[19].extension[0].extension[2].valueInteger = 1
* group[0].element[19].display = "Name of Second Alternate Coding System"
* group[0].element[19].target.equivalence = #equivalent
* group[0].element[19].target.code = #definition(DeviceDefinition.identifier[3].system)
* group[0].element[19].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[19].target.extension[0].extension[0].url = "assignment"
* group[0].element[19].target.extension[0].extension[0].valueString = "/map HL7 code system to appropriate url/"
* group[0].element[19].target.display = "definition(DeviceDefinition.identifier[3].system)"
* group[0].element[19].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[19].target.dependsOn[0].value = "If kind identifier"
