// HL7 Message - FHIR R4_ OML_O21 - Sheet1.csv
Instance: MessageOML_O21ToBundle
InstanceOf: ConceptMap
Title: "Message OML_O21 to Bundle Map"
Usage: #definition
* title = "Message OML_O21 to Bundle Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Message OML_O21 to the FHIR Message Bundle."
* id = "message-oml-o21-to-bundle"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/message-oml-o21-to-bundle"
* name = "MessageOML_O21ToBundle"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Message OML:O21 to Bundle.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1cSYLIXVfIjl7ib2DEGxD96LD9-YVJNQtKul5IwzJtts/edit#gid=0"
* group[0].element[0].code = #OML_O21.MSH
* group[0].element[0].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[0].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[0].extension[0].extension[0].valueInteger = 1
* group[0].element[0].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[0].extension[0].extension[1].valueInteger = 1
* group[0].element[0].display = "Message Header"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #Bundle
* group[0].element[0].target.display = "Bundle"
* group[0].element[1].code = #OML_O21.MSH
* group[0].element[1].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[1].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[1].extension[0].extension[0].valueInteger = 1
* group[0].element[1].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[1].extension[0].extension[1].valueInteger = 1
* group[0].element[1].display = "Message Header"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #MessageHeader[1]
* group[0].element[1].target.display = "MessageHeader[1]"
* group[0].element[1].target.comment = "Processing of the MSH segment results in the creation of a new MessageHeader resource"
* group[0].element[2].code = #OML_O21.MSH
* group[0].element[2].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[2].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[2].extension[0].extension[0].valueInteger = 1
* group[0].element[2].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[2].extension[0].extension[1].valueInteger = 1
* group[0].element[2].display = "Message Header"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #Provenance[1]
* group[0].element[2].target.display = "Provenance[1]"
* group[0].element[2].target.comment = "If the FHIR transformation does not yield a FHIR message, but only a set of resource (APIs, repository, etc.) than one should consider attaching this Provenance resource instance to the relevant FHIR resources generated."
* group[0].element[2].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[2].target.dependsOn[0].value = "If there is a source in MSH-4, or known based on the configuration."
* group[0].element[3].code = #OML_O21.MSH
* group[0].element[3].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[3].extension[0].extension[0].valueInteger = 1
* group[0].element[3].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[3].extension[0].extension[1].valueInteger = 1
* group[0].element[3].display = "Message Header"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #Provenance[2]
* group[0].element[3].target.display = "Provenance[2]"
* group[0].element[3].target.comment = "If the FHIR transformation does not yield a FHIR Bunlde, but only a set of resource (APIs, repository, etc.) than one should consider attaching this Provenance resource instance to the relevant FHIR resources generated."
* group[0].element[4].code = #OML_O21.SFT
* group[0].element[4].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[4].extension[0].extension[0].valueInteger = 0
* group[0].element[4].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[4].extension[0].extension[1].valueInteger = -1
* group[0].element[4].display = "Software"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #Provenance[1].entity.what(Device)
* group[0].element[4].target.display = "Provenance[1].entity.what(Device)"
* group[0].element[4].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[4].target.dependsOn[0].value = "If the software does represent not the original source system"
* group[0].element[5].code = #OML_O21.SFT
* group[0].element[5].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[5].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[5].extension[0].extension[0].valueInteger = 0
* group[0].element[5].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[5].extension[0].extension[1].valueInteger = -1
* group[0].element[5].display = "Software"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #Provenance[1].entity.what(Device)
* group[0].element[5].target.display = "Provenance[1].entity.what(Device)"
* group[0].element[5].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[5].target.dependsOn[0].value = "If the software represents the original source system"
* group[0].element[6].code = #OML_O21.PATIENT.PID
* group[0].element[6].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[6].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[6].extension[0].extension[0].valueInteger = 1
* group[0].element[6].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[6].extension[0].extension[1].valueInteger = 1
* group[0].element[6].display = "Patient Identification"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #Patient[1]
* group[0].element[6].target.display = "Patient[1]"
* group[0].element[6].target.comment = "Processing of the PID segment results in the creation of a new Patient resource"
* group[0].element[7].code = #OML_O21.PATIENT.PID
* group[0].element[7].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[7].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[7].extension[0].extension[0].valueInteger = 1
* group[0].element[7].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[7].extension[0].extension[1].valueInteger = 1
* group[0].element[7].display = "Patient Identification"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #Provenance[4]
* group[0].element[7].target.display = "Provenance[4]"
* group[0].element[7].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[7].target.dependsOn[0].value = "IF PID-33 AND PID-34 VALUED"
* group[0].element[7].target.dependsOn[1].property = "Narrative-Condition"
* group[0].element[7].target.dependsOn[1].value = "One  may drop PID-33 from the condition if PID-34 Last Update Facility is still sufficient without a date."
* group[0].element[8].code = #OML_O21.PATIENT.PD1
* group[0].element[8].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[8].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[8].extension[0].extension[0].valueInteger = 0
* group[0].element[8].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[8].extension[0].extension[1].valueInteger = 1
* group[0].element[8].display = "Additional Demographics"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #Patient[1]
* group[0].element[8].target.display = "Patient[1]"
* group[0].element[8].target.comment = "Incorporate PD1 content into the Patient created from the PID segment."
* group[0].element[9].code = #OML_O21.PATIENT.PD1
* group[0].element[9].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[9].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[9].extension[0].extension[0].valueInteger = 0
* group[0].element[9].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[9].extension[0].extension[1].valueInteger = 1
* group[0].element[9].display = "Additional Demographics"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #Observation[2]
* group[0].element[9].target.display = "Observation[2]"
* group[0].element[9].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[9].target.dependsOn[0].value = "IF PD1-7 VALUED"
* group[0].element[10].code = #OML_O21.PATIENT.PRT
* group[0].element[10].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[10].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[10].extension[0].extension[0].valueInteger = 0
* group[0].element[10].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[10].extension[0].extension[1].valueInteger = -1
* group[0].element[10].display = "Participation (for Patient)"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #PractitionerRole[1]
* group[0].element[10].target.display = "PractitionerRole[1]"
* group[0].element[10].target.comment = "Incorporate PRT content into the Patient created from the PID segment when the PRT contains practitioner related data."
* group[0].element[10].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[10].target.dependsOn[0].value = "IF PRT-4.1 EQUALS \"PP\" AND PRT-4.3 EQUALS \"HL70443\""
* group[0].element[10].target.dependsOn[1].property = "Computable-FHIRPath"
* group[0].element[10].target.dependsOn[1].value = "(element(\"4.1\")=\"PP\")and(element(\"4.3\")=\"HL70443\")"
* group[0].element[11].code = #OML_O21.PATIENT.PRT
* group[0].element[11].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[11].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[11].extension[0].extension[0].valueInteger = 0
* group[0].element[11].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[11].extension[0].extension[1].valueInteger = -1
* group[0].element[11].display = "Participation (for Patient)"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #RelatedPerson[1]
* group[0].element[11].target.display = "RelatedPerson[1]"
* group[0].element[11].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[11].target.dependsOn[0].value = "IF PRT-4.1 NOT EQUALS \"PP\" OR PRT-4.3 NOT EQUALS \"HL70443\""
* group[0].element[11].target.dependsOn[1].property = "Computable-FHIRPath"
* group[0].element[11].target.dependsOn[1].value = "(element(\"4.1\"!)=\"PP\")or(element(\"4.3\")!=\"HL70443\")"
* group[0].element[12].code = #OML_O21.PATIENT.NK1
* group[0].element[12].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[12].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[12].extension[0].extension[0].valueInteger = 0
* group[0].element[12].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[12].extension[0].extension[1].valueInteger = -1
* group[0].element[12].display = "Next of Kin/Associated Parties"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #RelatedPerson[2]
* group[0].element[12].target.display = "RelatedPerson[2]"
* group[0].element[12].target.comment = "Typically, each NK1 will be translated to either a new RelatedPerson resource or added as a new occurrence of Patient.contact, but it's possible to insert the NK1 data into both structures."
* group[0].element[12].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[12].target.dependsOn[0].value = "The FHIR location will depend on the nature of the data being exchanged and how the systems use next of kin data"
* group[0].element[13].code = #OML_O21.PATIENT.NK1
* group[0].element[13].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[13].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[13].extension[0].extension[0].valueInteger = 0
* group[0].element[13].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[13].extension[0].extension[1].valueInteger = -1
* group[0].element[13].display = "Next of Kin/Associated Parties"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #Patient[1]
* group[0].element[13].target.display = "Patient[1]"
* group[0].element[13].target.comment = "Typically, each NK1 will be translated to either a new RelatedPerson resource or added as a new occurrence of Patient.contact, but it's possible to insert the NK1 data into both structures."
* group[0].element[13].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[13].target.dependsOn[0].value = "The FHIR location will depend on the nature of the data being exchanged and how the systems use next of kin data"
* group[0].element[14].code = #OML_O21.PATIENT.PATIENT_VISIT.PV1
* group[0].element[14].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[14].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[14].extension[0].extension[0].valueInteger = 1
* group[0].element[14].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[14].extension[0].extension[1].valueInteger = 1
* group[0].element[14].display = "Patient Visit"
* group[0].element[14].target.equivalence = #equivalent
* group[0].element[14].target.code = #Encounter[1]
* group[0].element[14].target.display = "Encounter[1]"
* group[0].element[14].target.comment = "Processing of the PV1 segment results in the creation of a new Encounter resource"
* group[0].element[15].code = #OML_O21.PATIENT.PATIENT_VISIT.PV1
* group[0].element[15].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[15].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[15].extension[0].extension[0].valueInteger = 1
* group[0].element[15].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[15].extension[0].extension[1].valueInteger = 1
* group[0].element[15].display = "Patient Visit"
* group[0].element[15].target.equivalence = #equivalent
* group[0].element[15].target.code = #Basic
* group[0].element[15].target.display = "Basic"
* group[0].element[15].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[15].target.dependsOn[0].value = "IF PV1-43 VALUED"
* group[0].element[16].code = #OML_O21.PATIENT.PATIENT_VISIT.PV1
* group[0].element[16].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[16].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[16].extension[0].extension[0].valueInteger = 1
* group[0].element[16].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[16].extension[0].extension[1].valueInteger = 1
* group[0].element[16].display = "Patient Visit"
* group[0].element[16].target.equivalence = #equivalent
* group[0].element[16].target.code = #Patient[1]
* group[0].element[16].target.display = "Patient[1]"
* group[0].element[17].code = #OML_O21.PATIENT.PATIENT_VISIT.PV1
* group[0].element[17].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[17].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[17].extension[0].extension[0].valueInteger = 1
* group[0].element[17].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[17].extension[0].extension[1].valueInteger = 1
* group[0].element[17].display = "Patient Visit"
* group[0].element[17].target.equivalence = #equivalent
* group[0].element[17].target.code = #Coverage[1]
* group[0].element[17].target.display = "Coverage[1]"
* group[0].element[17].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[17].target.dependsOn[0].value = "IF PV1-20 VALUE"
* group[0].element[18].code = #OML_O21.PATIENT.PATIENT_VISIT.PV2
* group[0].element[18].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[18].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[18].extension[0].extension[0].valueInteger = 0
* group[0].element[18].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[18].extension[0].extension[1].valueInteger = 1
* group[0].element[18].display = "Patient Visit- Additional Info"
* group[0].element[18].target.equivalence = #equivalent
* group[0].element[18].target.code = #Encounter[1]
* group[0].element[18].target.display = "Encounter[1]"
* group[0].element[18].target.comment = "Incorporate PV2 content into the Encounter created from the PV1 segment."
* group[0].element[19].code = #OML_O21.PATIENT.PATIENT_VISIT.PRT
* group[0].element[19].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[19].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[19].extension[0].extension[0].valueInteger = 0
* group[0].element[19].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[19].extension[0].extension[1].valueInteger = -1
* group[0].element[19].display = "Participation (for Patient Visit)"
* group[0].element[19].target.equivalence = #equivalent
* group[0].element[19].target.code = #PractitionerRole[2]
* group[0].element[19].target.display = "PractitionerRole[2]"
* group[0].element[19].target.comment = "Incorporate PRT content into the Encounter created from the PV1 segment."
* group[0].element[20].code = #OML_O21.PATIENT.INSURANCE.IN1
* group[0].element[20].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[20].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[20].extension[0].extension[0].valueInteger = 1
* group[0].element[20].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[20].extension[0].extension[1].valueInteger = 1
* group[0].element[20].display = "Insurance"
* group[0].element[20].target.equivalence = #equivalent
* group[0].element[20].target.code = #Coverage[1]
* group[0].element[20].target.display = "Coverage[1]"
* group[0].element[20].target.comment = "Processing of the IN1 segment results in the creation of a new Coverage resource"
* group[0].element[21].code = #OML_O21.PATIENT.INSURANCE.IN3
* group[0].element[21].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[21].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[21].extension[0].extension[0].valueInteger = 0
* group[0].element[21].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[21].extension[0].extension[1].valueInteger = 1
* group[0].element[21].display = "Insurance Additional Information, Certification"
* group[0].element[21].target.equivalence = #equivalent
* group[0].element[21].target.code = #Coverage[1]
* group[0].element[21].target.display = "Coverage[1]"
* group[0].element[22].code = #OML_O21.PATIENT.AL1
* group[0].element[22].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[22].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[22].extension[0].extension[0].valueInteger = 0
* group[0].element[22].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[22].extension[0].extension[1].valueInteger = -1
* group[0].element[22].display = "Allergy Information"
* group[0].element[22].target.equivalence = #equivalent
* group[0].element[22].target.code = #AllergyIntolerance
* group[0].element[22].target.display = "AllergyIntolerance"
* group[0].element[22].target.comment = "Processing of the AL1 segment results in the creation of a new AllergyIntolerance resource"
* group[0].element[23].code = #OML_O21.ORDER.ORC
* group[0].element[23].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[23].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[23].extension[0].extension[0].valueInteger = 1
* group[0].element[23].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[23].extension[0].extension[1].valueInteger = 1
* group[0].element[23].display = "Common Order"
* group[0].element[23].target.equivalence = #equivalent
* group[0].element[23].target.code = #ServiceRequest[1]
* group[0].element[23].target.display = "ServiceRequest[1]"
* group[0].element[23].target.comment = "Processing of each ORC segment results in the creation of a new ServiceRequest resource"
* group[0].element[24].code = #OML_O21.ORDER.ORC
* group[0].element[24].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[24].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[24].extension[0].extension[0].valueInteger = 1
* group[0].element[24].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[24].extension[0].extension[1].valueInteger = 1
* group[0].element[24].display = "Common Order"
* group[0].element[24].target.equivalence = #equivalent
* group[0].element[24].target.code = #Provenance[3]
* group[0].element[24].target.display = "Provenance[3]"
* group[0].element[24].target.comment = "Using Provenance is the preferred way, but a local implementation may decide to add extensions to the main resource.  As the use and guidance of Provenance matures we wil revisit this later."
* group[0].element[25].code = #OML_O21.ORDER.PRT
* group[0].element[25].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[25].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[25].extension[0].extension[0].valueInteger = 0
* group[0].element[25].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[25].extension[0].extension[1].valueInteger = -1
* group[0].element[25].display = "Participation (for Common Order)"
* group[0].element[25].target.equivalence = #equivalent
* group[0].element[25].target.code = #PractitionerRole[3]
* group[0].element[25].target.display = "PractitionerRole[3]"
* group[0].element[25].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[25].target.dependsOn[0].value = "IF PRT-4.1 EQUALS \"OP\" AND PRT-4.3 EQUALS \"HL70443\""
* group[0].element[25].target.dependsOn[1].property = "Computable-FHIRPath"
* group[0].element[25].target.dependsOn[1].value = "(element(\"4.1\")=\"OP\")and(element(\"4.3\")=\"HL70443\")"
* group[0].element[26].code = #OML_O21.ORDER.TIMING.TQ1
* group[0].element[26].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[26].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[26].extension[0].extension[0].valueInteger = 1
* group[0].element[26].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[26].extension[0].extension[1].valueInteger = 1
* group[0].element[26].display = "Timing/Quantity"
* group[0].element[26].target.equivalence = #equivalent
* group[0].element[26].target.code = #ServiceRequest[1]
* group[0].element[26].target.display = "ServiceRequest[1]"
* group[0].element[27].code = #OML_O21.ORDER.OBSERVATION_REQUEST.OBR
* group[0].element[27].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[27].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[27].extension[0].extension[0].valueInteger = 1
* group[0].element[27].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[27].extension[0].extension[1].valueInteger = 1
* group[0].element[27].display = "Observation Request"
* group[0].element[27].target.equivalence = #equivalent
* group[0].element[27].target.code = #ServiceRequest[1]
* group[0].element[27].target.display = "ServiceRequest[1]"
* group[0].element[27].target.comment = "Incorporate OBR content into the ServiceRequest created from the ORC segment in the same segment group."
* group[0].element[28].code = #OML_O21.ORDER.OBSERVATION_REQUEST.OBR
* group[0].element[28].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[28].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[28].extension[0].extension[0].valueInteger = 1
* group[0].element[28].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[28].extension[0].extension[1].valueInteger = 1
* group[0].element[28].display = "Observation Request"
* group[0].element[28].target.equivalence = #equivalent
* group[0].element[28].target.code = #Specimen[each]
* group[0].element[28].target.display = "Specimen[each]"
* group[0].element[29].code = #OML_O21.ORDER.OBSERVATION_REQUEST.NTE
* group[0].element[29].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[29].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[29].extension[0].extension[0].valueInteger = 0
* group[0].element[29].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[29].extension[0].extension[1].valueInteger = -1
* group[0].element[29].display = "Notes and Comments (for Detail)"
* group[0].element[29].target.equivalence = #equivalent
* group[0].element[29].target.code = #ServiceRequest[1]
* group[0].element[29].target.display = "ServiceRequest[1]"
* group[0].element[30].code = #OML_O21.ORDER.OBSERVATION_REQUEST.PRT
* group[0].element[30].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[30].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[30].extension[0].extension[0].valueInteger = 0
* group[0].element[30].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[30].extension[0].extension[1].valueInteger = -1
* group[0].element[30].display = "Participation (for Observation Request)"
* group[0].element[30].target.equivalence = #equivalent
* group[0].element[30].target.code = #PractitionerRole[4]
* group[0].element[30].target.display = "PractitionerRole[4]"
* group[0].element[30].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[30].target.dependsOn[0].value = "IF PRT-4.1 EQUALS \"SC\" AND PRT-4.3 EQUALS \"HL70443\""
* group[0].element[30].target.dependsOn[1].property = "Computable-FHIRPath"
* group[0].element[30].target.dependsOn[1].value = "(element(\"4.1\")=\"SC\")and(element(\"4.3\")=\"HL70443\")"
* group[0].element[31].code = #OML_O21.ORDER.OBSERVATION_REQUEST.PRT
* group[0].element[31].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[31].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[31].extension[0].extension[0].valueInteger = 0
* group[0].element[31].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[31].extension[0].extension[1].valueInteger = -1
* group[0].element[31].display = "Participation (for Observation Request)"
* group[0].element[31].target.equivalence = #equivalent
* group[0].element[31].target.code = #PractitionerRole[3]
* group[0].element[31].target.display = "PractitionerRole[3]"
* group[0].element[31].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[31].target.dependsOn[0].value = "IF PRT-4.1 EQUALS \"OP\" AND PRT-4.3 EQUALS \"HL70443\""
* group[0].element[31].target.dependsOn[1].property = "Computable-FHIRPath"
* group[0].element[31].target.dependsOn[1].value = "(element(\"4.1\")=\"OP\")and(element(\"4.3\")=\"HL70443\")"
* group[0].element[32].code = #OML_O21.ORDER.OBSERVATION_REQUEST.DG1
* group[0].element[32].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[32].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[32].extension[0].extension[0].valueInteger = 0
* group[0].element[32].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[32].extension[0].extension[1].valueInteger = -1
* group[0].element[32].display = "Diagnosis"
* group[0].element[32].target.equivalence = #equivalent
* group[0].element[32].target.code = #Condition[1]
* group[0].element[32].target.display = "Condition[1]"
* group[0].element[32].target.comment = "Processing of the DG1 segment results in the creation of a new Condition resource which is referenced in the ServiceRequest created by the ORC segment"
* group[0].element[33].code = #OML_O21.ORDER.OBSERVATION_REQUEST.OBSERVATION.OBX
* group[0].element[33].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[33].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[33].extension[0].extension[0].valueInteger = 1
* group[0].element[33].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[33].extension[0].extension[1].valueInteger = 1
* group[0].element[33].display = "Observation/Result"
* group[0].element[33].target.equivalence = #equivalent
* group[0].element[33].target.code = #Observation[1]
* group[0].element[33].target.display = "Observation[1]"
* group[0].element[33].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[33].target.dependsOn[0].value = "IF OBX-5 LST.count LESS THAN OR EQUALS 1 OR OBX-2 IS \"NA\""
* group[0].element[34].code = #OML_O21.ORDER.OBSERVATION_REQUEST.OBSERVATION.OBX
* group[0].element[34].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[34].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[34].extension[0].extension[0].valueInteger = 1
* group[0].element[34].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[34].extension[0].extension[1].valueInteger = 1
* group[0].element[34].display = "Observation/Result"
* group[0].element[34].target.equivalence = #equivalent
* group[0].element[34].target.code = #Observation[1]
* group[0].element[34].target.display = "Observation[1]"
* group[0].element[34].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[34].target.dependsOn[0].value = "IF  OBX-5 LST.count GREATER THAN 1 AND OBX-2 IS NOT \"NA\""
* group[0].element[35].code = #OML_O21.ORDER.OBSERVATION_REQUEST.OBSERVATION.PRT
* group[0].element[35].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[35].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[35].extension[0].extension[0].valueInteger = 0
* group[0].element[35].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[35].extension[0].extension[1].valueInteger = -1
* group[0].element[35].display = "Participation (for OBX)"
* group[0].element[35].target.equivalence = #equivalent
* group[0].element[35].target.code = #Device[1]
* group[0].element[35].target.display = "Device[1]"
* group[0].element[35].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[35].target.dependsOn[0].value = "IF PRT-10 VALUED"
* group[0].element[36].code = #OML_O21.ORDER.OBSERVATION_REQUEST.OBSERVATION.PRT
* group[0].element[36].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[36].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[36].extension[0].extension[0].valueInteger = 0
* group[0].element[36].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[36].extension[0].extension[1].valueInteger = -1
* group[0].element[36].display = "Participation (for OBX)"
* group[0].element[36].target.equivalence = #equivalent
* group[0].element[36].target.code = #Observation[1]
* group[0].element[36].target.display = "Observation[1]"
* group[0].element[36].target.comment = "Incorporate PRT content into the Observation created from the OBX segment in the same segment group when it represents observation location information."
* group[0].element[36].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[36].target.dependsOn[0].value = "IF PRT-9 VALUED OR IF PRT-14 VALUED"
* group[0].element[37].code = #OML_O21.ORDER.OBSERVATION_REQUEST.OBSERVATION.PRT
* group[0].element[37].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[37].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[37].extension[0].extension[0].valueInteger = 0
* group[0].element[37].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[37].extension[0].extension[1].valueInteger = -1
* group[0].element[37].display = "Participation (for OBX)"
* group[0].element[37].target.equivalence = #equivalent
* group[0].element[37].target.code = #PractitionerRole[7]
* group[0].element[37].target.display = "PractitionerRole[7]"
* group[0].element[37].target.comment = "Incorporate PRT content into the Observation created from the OBX segment in the same segment group when it represents observation practitioner information."
* group[0].element[37].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[37].target.dependsOn[0].value = "IF PRT-5 VALUED"
* group[0].element[38].code = #OML_O21.ORDER.OBSERVATION_REQUEST.OBSERVATION.NTE
* group[0].element[38].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[38].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[38].extension[0].extension[0].valueInteger = 0
* group[0].element[38].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[38].extension[0].extension[1].valueInteger = -1
* group[0].element[38].display = "Notes and Comments (for Results)"
* group[0].element[38].target.equivalence = #equivalent
* group[0].element[38].target.code = #Observation[1]
* group[0].element[38].target.display = "Observation[1]"
* group[0].element[39].code = #OML_O21.ORDER.OBSERVATION_REQUEST.SPECIMEN.SPM
* group[0].element[39].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[39].extension[0].extension[0].url = "cardinalityMin"
* group[0].element[39].extension[0].extension[0].valueInteger = 1
* group[0].element[39].extension[0].extension[1].url = "cardinalityMax"
* group[0].element[39].extension[0].extension[1].valueInteger = 1
* group[0].element[39].display = "Specimen"
* group[0].element[39].target.equivalence = #equivalent
* group[0].element[39].target.code = #Specimen
* group[0].element[39].target.display = "Specimen"
