// HL7 Segment - FHIR R4_ SCH[Appointment] - Sheet1.csv
Instance: SegmentSCHToAppointment
InstanceOf: ConceptMap
Title: "Segment SCH to Appointment Map"
Usage: #definition
* title = "Segment SCH to Appointment Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Segment SCH to the FHIR Appointment Resource."
* id = "segment-sch-to-appointment"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/segment-sch-to-appointment"
* name = "SegmentSCHToAppointment"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Segment SCH to Appointment.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1S47XTStisnXo1osyf8tR8yDySkWM1tb4MFrHIU1Es48/edit#gid=0"
* group[0].element[0].code = #SCH-1
* group[0].element[0].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[0].extension[0].extension[0].url = "type"
* group[0].element[0].extension[0].extension[0].valueCode = #"EI"
* group[0].element[0].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[0].extension[0].extension[1].valueInteger = 1
* group[0].element[0].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[0].extension[0].extension[2].valueInteger = 1
* group[0].element[0].display = "Placer Appointment ID"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #identifier[1]
* group[0].element[0].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[0].target.extension[0].extension[0].url = "type"
* group[0].element[0].target.extension[0].extension[0].valueCode = #"Identifier"
* group[0].element[0].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[0].target.extension[0].extension[1].valueInteger = 0
* group[0].element[0].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[0].target.extension[0].extension[2].valueInteger = -1
* group[0].element[0].target.display = "identifier[1]"
* group[0].element[1].code = #SCH-2
* group[0].element[1].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[1].extension[0].extension[0].url = "type"
* group[0].element[1].extension[0].extension[0].valueCode = #"EI"
* group[0].element[1].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[1].extension[0].extension[1].valueInteger = 1
* group[0].element[1].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[1].extension[0].extension[2].valueInteger = 1
* group[0].element[1].display = "Filler Appointment ID"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #identifier[2]
* group[0].element[1].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[1].target.extension[0].extension[0].url = "type"
* group[0].element[1].target.extension[0].extension[0].valueCode = #"Identifier"
* group[0].element[1].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[1].target.extension[0].extension[1].valueInteger = 0
* group[0].element[1].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[1].target.extension[0].extension[2].valueInteger = -1
* group[0].element[1].target.display = "identifier[2]"
* group[0].element[2].code = #SCH-7
* group[0].element[2].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[2].extension[0].extension[0].url = "type"
* group[0].element[2].extension[0].extension[0].valueCode = #"CWE"
* group[0].element[2].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[2].extension[0].extension[1].valueInteger = 1
* group[0].element[2].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[2].extension[0].extension[2].valueInteger = 1
* group[0].element[2].display = "Appointment Reason"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #reasonCode[1]
* group[0].element[2].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[2].target.extension[0].extension[0].url = "type"
* group[0].element[2].target.extension[0].extension[0].valueCode = #"CodeableConcept"
* group[0].element[2].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[2].target.extension[0].extension[1].valueInteger = 0
* group[0].element[2].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[2].target.extension[0].extension[2].valueInteger = -1
* group[0].element[2].target.extension[0].extension[3].url = "mappedVia"
* group[0].element[2].target.extension[0].extension[3].valueUrl = "ConceptMap/table-hl70276-to-sct"
* group[0].element[2].target.display = "reasonCode[1]"
* group[0].element[2].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[2].target.dependsOn[0].value = "IF CWE.3 IS \"HL70276\""
* group[0].element[3].code = #SCH-7
* group[0].element[3].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].extension[0].extension[0].url = "type"
* group[0].element[3].extension[0].extension[0].valueCode = #"CWE"
* group[0].element[3].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[3].extension[0].extension[1].valueInteger = 1
* group[0].element[3].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[3].extension[0].extension[2].valueInteger = 1
* group[0].element[3].display = "Appointment Reason"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #appointmentType[1]
* group[0].element[3].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].target.extension[0].extension[0].url = "type"
* group[0].element[3].target.extension[0].extension[0].valueCode = #"CodeableConcept"
* group[0].element[3].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[3].target.extension[0].extension[1].valueInteger = 0
* group[0].element[3].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[3].target.extension[0].extension[2].valueInteger = 1
* group[0].element[3].target.extension[0].extension[3].url = "mappedVia"
* group[0].element[3].target.extension[0].extension[3].valueUrl = "ConceptMap/table-hl70277-to-v2-0277"
* group[0].element[3].target.display = "appointmentType[1]"
* group[0].element[3].target.comment = "Note that in V2 this is Table HL70276, but there is a problem with that as it does not reflect SCH-7, rather SCH-8.  We are working on correcting that in HL7 v2."
* group[0].element[3].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[3].target.dependsOn[0].value = "IF CWE.3 IS \"HL70277\""
* group[0].element[4].code = #SCH-8
* group[0].element[4].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].extension[0].extension[0].url = "type"
* group[0].element[4].extension[0].extension[0].valueCode = #"CWE"
* group[0].element[4].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[4].extension[0].extension[1].valueInteger = 1
* group[0].element[4].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[4].extension[0].extension[2].valueInteger = 1
* group[0].element[4].display = "Appointment Type"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #appointmentType[1]
* group[0].element[4].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].target.extension[0].extension[0].url = "type"
* group[0].element[4].target.extension[0].extension[0].valueCode = #"CodeableConcept"
* group[0].element[4].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[4].target.extension[0].extension[1].valueInteger = 0
* group[0].element[4].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[4].target.extension[0].extension[2].valueInteger = 1
* group[0].element[4].target.extension[0].extension[3].url = "mappedVia"
* group[0].element[4].target.extension[0].extension[3].valueUrl = "ConceptMap/table-hl70277-to-v2-0277"
* group[0].element[4].target.display = "appointmentType[1]"
* group[0].element[4].target.comment = "Note that in V2 this is Table HL70276, but there is a problem with that as it does not reflect SCH-7, rather SCH-8.  We are working on correcting that in HL7 v2."
* group[0].element[4].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[4].target.dependsOn[0].value = "IF CWE.3 IS \"HL70277\""
* group[0].element[5].code = #SCH-9
* group[0].element[5].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[5].extension[0].extension[0].url = "type"
* group[0].element[5].extension[0].extension[0].valueCode = #"NM"
* group[0].element[5].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[5].extension[0].extension[1].valueInteger = -1
* group[0].element[5].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[5].extension[0].extension[2].valueInteger = -1
* group[0].element[5].display = "Appointment Duration"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #minutesDuration[1]
* group[0].element[5].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[5].target.extension[0].extension[0].url = "type"
* group[0].element[5].target.extension[0].extension[0].valueCode = #"positiveInt"
* group[0].element[5].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[5].target.extension[0].extension[1].valueInteger = 0
* group[0].element[5].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[5].target.extension[0].extension[2].valueInteger = 1
* group[0].element[5].target.display = "minutesDuration[1]"
* group[0].element[5].target.dependsOn[0].property = "Narrative-Condition"
* group[0].element[5].target.dependsOn[0].value = "If SCH-10 indicates units of minutes"
* group[0].element[6].code = #SCH-11
* group[0].element[6].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[6].extension[0].extension[0].url = "type"
* group[0].element[6].extension[0].extension[0].valueCode = #"TQ"
* group[0].element[6].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[6].extension[0].extension[1].valueInteger = -1
* group[0].element[6].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[6].extension[0].extension[2].valueInteger = -1
* group[0].element[6].display = "Appointment Timing Quantity"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #$this
* group[0].element[6].target.display = "$this"
* group[0].element[7].code = #SCH-12
* group[0].element[7].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[7].extension[0].extension[0].url = "type"
* group[0].element[7].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[7].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[7].extension[0].extension[1].valueInteger = -1
* group[0].element[7].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[7].extension[0].extension[2].valueInteger = -1
* group[0].element[7].display = "Placer Contact Person"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #participant[1].actor(Practitioner)
* group[0].element[7].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[7].target.extension[0].extension[0].url = "type"
* group[0].element[7].target.extension[0].extension[0].valueCode = #"Reference(Practitioner)"
* group[0].element[7].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[7].target.extension[0].extension[1].valueInteger = 0
* group[0].element[7].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[7].target.extension[0].extension[2].valueInteger = 1
* group[0].element[7].target.display = "participant[1].actor(Practitioner)"
* group[0].element[8].code = #SCH-12
* group[0].element[8].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[8].extension[0].extension[0].url = "type"
* group[0].element[8].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[8].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[8].extension[0].extension[1].valueInteger = -1
* group[0].element[8].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[8].extension[0].extension[2].valueInteger = -1
* group[0].element[8].display = "Placer Contact Person"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #participant[1].type.coding.code
* group[0].element[8].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[8].target.extension[0].extension[0].url = "assignment"
* group[0].element[8].target.extension[0].extension[0].valueString = "#placer contact#"
* group[0].element[8].target.display = "participant[1].type.coding.code"
* group[0].element[9].code = #SCH-12
* group[0].element[9].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[9].extension[0].extension[0].url = "type"
* group[0].element[9].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[9].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[9].extension[0].extension[1].valueInteger = -1
* group[0].element[9].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[9].extension[0].extension[2].valueInteger = -1
* group[0].element[9].display = "Placer Contact Person"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #participant[1].type.coding.system
* group[0].element[9].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[9].target.extension[0].extension[0].url = "assignment"
* group[0].element[9].target.extension[0].extension[0].valueString = "\"http://terminology.hl7.org/CodeSystem/participant-type\""
* group[0].element[9].target.display = "participant[1].type.coding.system"
* group[0].element[10].code = #SCH-16
* group[0].element[10].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[10].extension[0].extension[0].url = "type"
* group[0].element[10].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[10].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[10].extension[0].extension[1].valueInteger = -1
* group[0].element[10].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[10].extension[0].extension[2].valueInteger = -1
* group[0].element[10].display = "Filler Contact Person"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #participant[2].actor(Practitioner)
* group[0].element[10].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[10].target.extension[0].extension[0].url = "type"
* group[0].element[10].target.extension[0].extension[0].valueCode = #"Reference(Practitioner)"
* group[0].element[10].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[10].target.extension[0].extension[1].valueInteger = 0
* group[0].element[10].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[10].target.extension[0].extension[2].valueInteger = 1
* group[0].element[10].target.display = "participant[2].actor(Practitioner)"
* group[0].element[11].code = #SCH-16
* group[0].element[11].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[11].extension[0].extension[0].url = "type"
* group[0].element[11].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[11].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[11].extension[0].extension[1].valueInteger = -1
* group[0].element[11].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[11].extension[0].extension[2].valueInteger = -1
* group[0].element[11].display = "Filler Contact Person"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #participant[2].type.coding.code
* group[0].element[11].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[11].target.extension[0].extension[0].url = "assignment"
* group[0].element[11].target.extension[0].extension[0].valueString = "#filler contact#"
* group[0].element[11].target.display = "participant[2].type.coding.code"
* group[0].element[12].code = #SCH-16
* group[0].element[12].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[12].extension[0].extension[0].url = "type"
* group[0].element[12].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[12].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[12].extension[0].extension[1].valueInteger = -1
* group[0].element[12].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[12].extension[0].extension[2].valueInteger = -1
* group[0].element[12].display = "Filler Contact Person"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #participant[2].type.coding.system
* group[0].element[12].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[12].target.extension[0].extension[0].url = "assignment"
* group[0].element[12].target.extension[0].extension[0].valueString = "\"http://terminology.hl7.org/CodeSystem/participant-type\""
* group[0].element[12].target.display = "participant[2].type.coding.system"
* group[0].element[13].code = #SCH-20
* group[0].element[13].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[13].extension[0].extension[0].url = "type"
* group[0].element[13].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[13].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[13].extension[0].extension[1].valueInteger = -1
* group[0].element[13].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[13].extension[0].extension[2].valueInteger = -1
* group[0].element[13].display = "Entered By Person"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #participant[3].actor(Practitioner)
* group[0].element[13].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[13].target.extension[0].extension[0].url = "type"
* group[0].element[13].target.extension[0].extension[0].valueCode = #"Reference(Practitioner)"
* group[0].element[13].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[13].target.extension[0].extension[1].valueInteger = 0
* group[0].element[13].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[13].target.extension[0].extension[2].valueInteger = 1
* group[0].element[13].target.display = "participant[3].actor(Practitioner)"
* group[0].element[14].code = #SCH-20
* group[0].element[14].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[14].extension[0].extension[0].url = "type"
* group[0].element[14].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[14].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[14].extension[0].extension[1].valueInteger = -1
* group[0].element[14].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[14].extension[0].extension[2].valueInteger = -1
* group[0].element[14].display = "Entered By Person"
* group[0].element[14].target.equivalence = #equivalent
* group[0].element[14].target.code = #participant[3].type[1].coding.code
* group[0].element[14].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[14].target.extension[0].extension[0].url = "assignment"
* group[0].element[14].target.extension[0].extension[0].valueString = "enterer"
* group[0].element[14].target.display = "participant[3].type[1].coding.code"
* group[0].element[15].code = #SCH-20
* group[0].element[15].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[15].extension[0].extension[0].url = "type"
* group[0].element[15].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[15].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[15].extension[0].extension[1].valueInteger = -1
* group[0].element[15].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[15].extension[0].extension[2].valueInteger = -1
* group[0].element[15].display = "Entered By Person"
* group[0].element[15].target.equivalence = #equivalent
* group[0].element[15].target.code = #participant[3].type[1].coding.system
* group[0].element[15].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[15].target.extension[0].extension[0].url = "assignment"
* group[0].element[15].target.extension[0].extension[0].valueString = "http://terminology.hl7.org/CodeSystem/provenance-participant-type"
* group[0].element[15].target.display = "participant[3].type[1].coding.system"
* group[0].element[16].code = #SCH-25
* group[0].element[16].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[16].extension[0].extension[0].url = "type"
* group[0].element[16].extension[0].extension[0].valueCode = #"CWE"
* group[0].element[16].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[16].extension[0].extension[1].valueInteger = 1
* group[0].element[16].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[16].extension[0].extension[2].valueInteger = 1
* group[0].element[16].display = "Filler Status Code"
* group[0].element[16].target.equivalence = #equivalent
* group[0].element[16].target.code = #status
* group[0].element[16].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[16].target.extension[0].extension[0].url = "type"
* group[0].element[16].target.extension[0].extension[0].valueCode = #"code"
* group[0].element[16].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[16].target.extension[0].extension[1].valueInteger = 1
* group[0].element[16].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[16].target.extension[0].extension[2].valueInteger = 1
* group[0].element[16].target.extension[0].extension[3].url = "mappedVia"
* group[0].element[16].target.extension[0].extension[3].valueUrl = "ConceptMap/table-hl70278-to-appointmentstatus"
* group[0].element[16].target.display = "status"
* group[0].element[17].code = #SCH-26
* group[0].element[17].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[17].extension[0].extension[0].url = "type"
* group[0].element[17].extension[0].extension[0].valueCode = #"EI"
* group[0].element[17].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[17].extension[0].extension[1].valueInteger = -1
* group[0].element[17].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[17].extension[0].extension[2].valueInteger = -1
* group[0].element[17].display = "Placer Order Number"
* group[0].element[17].target.equivalence = #equivalent
* group[0].element[17].target.code = #basedOn(ServiceRequest)
* group[0].element[17].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[17].target.extension[0].extension[0].url = "type"
* group[0].element[17].target.extension[0].extension[0].valueCode = #"Reference(ServiceRequest)"
* group[0].element[17].target.display = "basedOn(ServiceRequest)"
* group[0].element[17].target.comment = "If valued, make sure that Appointment.basedOn is used to link to the ServiceRequest"
* group[0].element[18].code = #SCH-27
* group[0].element[18].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[18].extension[0].extension[0].url = "type"
* group[0].element[18].extension[0].extension[0].valueCode = #"EI"
* group[0].element[18].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[18].extension[0].extension[1].valueInteger = -1
* group[0].element[18].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[18].extension[0].extension[2].valueInteger = -1
* group[0].element[18].display = "Filler Order Number"
* group[0].element[18].target.equivalence = #equivalent
* group[0].element[18].target.code = #basedOn(ServiceRequest)
* group[0].element[18].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[18].target.extension[0].extension[0].url = "type"
* group[0].element[18].target.extension[0].extension[0].valueCode = #"Reference(ServiceRequest)"
* group[0].element[18].target.display = "basedOn(ServiceRequest)"
* group[0].element[18].target.comment = "If valued, make sure that Appointment.basedOn is used to link to the ServiceRequest"
