// HL7 Segment - FHIR R4_ AIP[Appointment] - Sheet1.csv
Instance: SegmentAIPToAppointment
InstanceOf: ConceptMap
Title: "Segment AIP to Appointment Map"
Usage: #definition
* title = "Segment AIP to Appointment Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Segment AIP to the FHIR Appointment Resource."
* id = "segment-aip-to-appointment"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/segment-aip-to-appointment"
* name = "SegmentAIPToAppointment"
* insert PublicationData
* group[0].element[0].code = #AIP-3
* group[0].element[0].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[0].extension[0].extension[0].url = "type"
* group[0].element[0].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[0].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[0].extension[0].extension[1].valueInteger = 1
* group[0].element[0].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[0].extension[0].extension[2].valueInteger = 1
* group[0].element[0].display = "Personnel Resource ID"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #participant.actor[1]
* group[0].element[0].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[0].target.extension[0].extension[0].url = "type"
* group[0].element[0].target.extension[0].extension[0].valueCode = #"Reference(Practitioner)"
* group[0].element[0].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[0].target.extension[0].extension[1].valueInteger = 0
* group[0].element[0].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[0].target.extension[0].extension[2].valueInteger = 1
* group[0].element[0].target.display = "participant.actor[1]"
* group[0].element[1].code = #AIP-4
* group[0].element[1].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[1].extension[0].extension[0].url = "type"
* group[0].element[1].extension[0].extension[0].valueCode = #"CWE"
* group[0].element[1].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[1].extension[0].extension[1].valueInteger = 1
* group[0].element[1].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[1].extension[0].extension[2].valueInteger = 1
* group[0].element[1].display = "Resource Type"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #participant.type[1]
* group[0].element[1].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[1].target.extension[0].extension[0].url = "type"
* group[0].element[1].target.extension[0].extension[0].valueCode = #"CodeableConcept"
* group[0].element[1].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[1].target.extension[0].extension[1].valueInteger = 0
* group[0].element[1].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[1].target.extension[0].extension[2].valueInteger = -1
* group[0].element[1].target.extension[0].extension[3].url = "assignment"
* group[0].element[1].target.extension[0].extension[3].valueString = "https://www.hl7.org/fhir/valueset-encounter-participant-type.html"
* group[0].element[1].target.display = "participant.type[1]"
* group[0].element[2].code = #AIP-6
* group[0].element[2].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[2].extension[0].extension[0].url = "type"
* group[0].element[2].extension[0].extension[0].valueCode = #"DTM"
* group[0].element[2].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[2].extension[0].extension[1].valueInteger = 1
* group[0].element[2].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[2].extension[0].extension[2].valueInteger = 1
* group[0].element[2].display = "Start Date/Time"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #participant.period.start
* group[0].element[2].target.display = "participant.period.start"
* group[0].element[3].code = #AIP-7
* group[0].element[3].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].extension[0].extension[0].url = "type"
* group[0].element[3].extension[0].extension[0].valueCode = #"NM"
* group[0].element[3].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[3].extension[0].extension[1].valueInteger = 1
* group[0].element[3].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[3].extension[0].extension[2].valueInteger = 1
* group[0].element[3].display = "Start Date/Time Offset"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #participant.period.start
* group[0].element[3].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].target.extension[0].extension[0].url = "assignment"
* group[0].element[3].target.extension[0].extension[0].valueString = "/.start + AIP-7 according to AIP-8 units/"
* group[0].element[3].target.display = "participant.period.start"
* group[0].element[3].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[3].target.dependsOn[0].value = "IF AIP-6 NOT VALUED"
* group[0].element[4].code = #AIP-9
* group[0].element[4].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].extension[0].extension[0].url = "type"
* group[0].element[4].extension[0].extension[0].valueCode = #"NM"
* group[0].element[4].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[4].extension[0].extension[1].valueInteger = 1
* group[0].element[4].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[4].extension[0].extension[2].valueInteger = 1
* group[0].element[4].display = "Duration"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #participant.period.end
* group[0].element[4].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].target.extension[0].extension[0].url = "assignment"
* group[0].element[4].target.extension[0].extension[0].valueString = "Appointment.participant.period.start + AIP-9"
* group[0].element[4].target.display = "participant.period.end"
* group[0].element[4].target.dependsOn[0].property = "Computable-ANTLR"
* group[0].element[4].target.dependsOn[0].value = "IF AIP-6 IS VALUED"
* group[0].element[5].code = #AIP-12
* group[0].element[5].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[5].extension[0].extension[0].url = "type"
* group[0].element[5].extension[0].extension[0].valueCode = #"CWE"
* group[0].element[5].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[5].extension[0].extension[1].valueInteger = 1
* group[0].element[5].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[5].extension[0].extension[2].valueInteger = 1
* group[0].element[5].display = "Filler Status Code"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #participant.status[1]
* group[0].element[5].target.display = "participant.status[1]"
