// HL7 Segment - FHIR R4_ DG1[EpisodeOfCare] - Sheet1.csv
Instance: SegmentDG1ToEpisodeOfCare
InstanceOf: ConceptMap
Title: "Segment DG1 to EpisodeOfCare Map"
Usage: #definition
* title = "Segment DG1 to EpisodeOfCare Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Segment DG1 to the FHIR EpisodeOfCare Resource."
* id = "segment-dg1-to-episodeofcare"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/segment-dg1-to-episodeofcare"
* name = "SegmentDG1ToEpisodeOfCare"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Segment DG1 to EpisodeOfCare.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1seZccIaX-x7-8vVxT1JiiG5Hm1dtWgYcI2RxiiKzh-o/edit#gid=0"
* group[0].element[0].code = #DG1-3
* group[0].element[0].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[0].extension[0].extension[0].url = "type"
* group[0].element[0].extension[0].extension[0].valueCode = #"CWE"
* group[0].element[0].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[0].extension[0].extension[1].valueInteger = 1
* group[0].element[0].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[0].extension[0].extension[2].valueInteger = 1
* group[0].element[0].display = "Diagnosis Code"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #diagnosis.condition(Condition.code)
* group[0].element[0].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[0].target.extension[0].extension[0].url = "type"
* group[0].element[0].target.extension[0].extension[0].valueCode = #"CodeableConcept"
* group[0].element[0].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[0].target.extension[0].extension[1].valueInteger = 0
* group[0].element[0].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[0].target.extension[0].extension[2].valueInteger = 1
* group[0].element[0].target.display = "diagnosis.condition(Condition.code)"
* group[0].element[1].code = #DG1-4
* group[0].element[1].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[1].extension[0].extension[0].url = "type"
* group[0].element[1].extension[0].extension[0].valueCode = #"ST"
* group[0].element[1].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[1].extension[0].extension[1].valueInteger = 1
* group[0].element[1].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[1].extension[0].extension[2].valueInteger = 1
* group[0].element[1].display = "Diagnosis Description"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #diagnosis.condition(Condition.code.text)
* group[0].element[1].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[1].target.extension[0].extension[0].url = "cardinalityMin"
* group[0].element[1].target.extension[0].extension[0].valueInteger = 0
* group[0].element[1].target.extension[0].extension[1].url = "cardinalityMax"
* group[0].element[1].target.extension[0].extension[1].valueInteger = 1
* group[0].element[1].target.display = "diagnosis.condition(Condition.code.text)"
* group[0].element[1].target.comment = "Doesn't warrant mapping"
* group[0].element[2].code = #DG1-5
* group[0].element[2].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[2].extension[0].extension[0].url = "type"
* group[0].element[2].extension[0].extension[0].valueCode = #"DTM"
* group[0].element[2].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[2].extension[0].extension[1].valueInteger = 1
* group[0].element[2].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[2].extension[0].extension[2].valueInteger = 1
* group[0].element[2].display = "Diagnosis Date/Time"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #diagnosis.condition(Condition.onsetDateTime)
* group[0].element[2].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[2].target.extension[0].extension[0].url = "type"
* group[0].element[2].target.extension[0].extension[0].valueCode = #"dateTime"
* group[0].element[2].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[2].target.extension[0].extension[1].valueInteger = 0
* group[0].element[2].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[2].target.extension[0].extension[2].valueInteger = 1
* group[0].element[2].target.display = "diagnosis.condition(Condition.onsetDateTime)"
* group[0].element[2].target.comment = "Should confirm that these two concepts are equivalent. Condition.recordedDate is also available"
* group[0].element[3].code = #DG1-6
* group[0].element[3].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].extension[0].extension[0].url = "type"
* group[0].element[3].extension[0].extension[0].valueCode = #"CWE"
* group[0].element[3].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[3].extension[0].extension[1].valueInteger = 1
* group[0].element[3].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[3].extension[0].extension[2].valueInteger = 1
* group[0].element[3].display = "Diagnosis Type"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #diagnosis.role
* group[0].element[3].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[3].target.extension[0].extension[0].url = "type"
* group[0].element[3].target.extension[0].extension[0].valueCode = #"CodeableConcept"
* group[0].element[3].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[3].target.extension[0].extension[1].valueInteger = 0
* group[0].element[3].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[3].target.extension[0].extension[2].valueInteger = 1
* group[0].element[3].target.extension[0].extension[3].url = "mappedVia"
* group[0].element[3].target.extension[0].extension[3].valueUrl = "ConceptMap/table-hl70052-to-diagnosis-role"
* group[0].element[3].target.display = "diagnosis.role"
* group[0].element[4].code = #DG1-15
* group[0].element[4].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].extension[0].extension[0].url = "type"
* group[0].element[4].extension[0].extension[0].valueCode = #"NM"
* group[0].element[4].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[4].extension[0].extension[1].valueInteger = 1
* group[0].element[4].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[4].extension[0].extension[2].valueInteger = 1
* group[0].element[4].display = "Diagnosis Priority"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #diagnosis.rank
* group[0].element[4].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[4].target.extension[0].extension[0].url = "type"
* group[0].element[4].target.extension[0].extension[0].valueCode = #"positiveInt"
* group[0].element[4].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[4].target.extension[0].extension[1].valueInteger = 0
* group[0].element[4].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[4].target.extension[0].extension[2].valueInteger = 1
* group[0].element[4].target.display = "diagnosis.rank"
* group[0].element[4].target.comment = "Could contribute to Condition.category or be a new extension"
* group[0].element[5].code = #DG1-16
* group[0].element[5].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[5].extension[0].extension[0].url = "type"
* group[0].element[5].extension[0].extension[0].valueCode = #"XCN"
* group[0].element[5].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[5].extension[0].extension[1].valueInteger = -1
* group[0].element[5].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[5].extension[0].extension[2].valueInteger = -1
* group[0].element[5].display = "Diagnosing Clinician"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #diagnosis.condition(Condition.asserter(Practitioner)
* group[0].element[5].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[5].target.extension[0].extension[0].url = "type"
* group[0].element[5].target.extension[0].extension[0].valueCode = #"Reference"
* group[0].element[5].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[5].target.extension[0].extension[1].valueInteger = 0
* group[0].element[5].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[5].target.extension[0].extension[2].valueInteger = 1
* group[0].element[5].target.display = "diagnosis.condition(Condition.asserter(Practitioner)"
* group[0].element[5].target.comment = "While DG1-16 can repeat, we are not aware of instances where this is used.  Until such time, we will not yet establish an agreed to method to communicate the extra repeats in FHIR."
* group[0].element[6].code = #DG1-19
* group[0].element[6].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[6].extension[0].extension[0].url = "type"
* group[0].element[6].extension[0].extension[0].valueCode = #"DTM"
* group[0].element[6].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[6].extension[0].extension[1].valueInteger = 1
* group[0].element[6].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[6].extension[0].extension[2].valueInteger = 1
* group[0].element[6].display = "Attestation Date/Time"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #diagnosis.condition(Condition.extension[1].url)
* group[0].element[6].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[6].target.extension[0].extension[0].url = "type"
* group[0].element[6].target.extension[0].extension[0].valueCode = #"uri"
* group[0].element[6].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[6].target.extension[0].extension[1].valueInteger = 1
* group[0].element[6].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[6].target.extension[0].extension[2].valueInteger = 1
* group[0].element[6].target.extension[0].extension[3].url = "assignment"
* group[0].element[6].target.extension[0].extension[3].valueString = "\"http://hl7.org/fhir/StructureDefinition/condition-assertedDate\""
* group[0].element[6].target.display = "diagnosis.condition(Condition.extension[1].url)"
* group[0].element[7].code = #DG1-19
* group[0].element[7].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[7].extension[0].extension[0].url = "type"
* group[0].element[7].extension[0].extension[0].valueCode = #"DTM"
* group[0].element[7].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[7].extension[0].extension[1].valueInteger = 1
* group[0].element[7].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[7].extension[0].extension[2].valueInteger = 1
* group[0].element[7].display = "Attestation Date/Time"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #diagnosis.condition(Condition.extension[1].valueDateTime)
* group[0].element[7].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[7].target.extension[0].extension[0].url = "type"
* group[0].element[7].target.extension[0].extension[0].valueCode = #"dateTime"
* group[0].element[7].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[7].target.extension[0].extension[1].valueInteger = 1
* group[0].element[7].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[7].target.extension[0].extension[2].valueInteger = 1
* group[0].element[7].target.display = "diagnosis.condition(Condition.extension[1].valueDateTime)"
* group[0].element[7].target.comment = "It is unclear whether to use recorded or asserted date.  What is your opinion?"
* group[0].element[8].code = #DG1-19
* group[0].element[8].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[8].extension[0].extension[0].url = "type"
* group[0].element[8].extension[0].extension[0].valueCode = #"DTM"
* group[0].element[8].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[8].extension[0].extension[1].valueInteger = 1
* group[0].element[8].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[8].extension[0].extension[2].valueInteger = 1
* group[0].element[8].display = "Attestation Date/Time"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #diagnosis.condition(Condition.recordedDate)
* group[0].element[8].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[8].target.extension[0].extension[0].url = "type"
* group[0].element[8].target.extension[0].extension[0].valueCode = #"dateTime"
* group[0].element[8].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[8].target.extension[0].extension[1].valueInteger = 0
* group[0].element[8].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[8].target.extension[0].extension[2].valueInteger = 1
* group[0].element[8].target.display = "diagnosis.condition(Condition.recordedDate)"
* group[0].element[8].target.comment = "It is unclear whether to use recorded or asserted date.  What is your opinion?"
* group[0].element[9].code = #DG1-20
* group[0].element[9].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[9].extension[0].extension[0].url = "type"
* group[0].element[9].extension[0].extension[0].valueCode = #"EI"
* group[0].element[9].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[9].extension[0].extension[1].valueInteger = 1
* group[0].element[9].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[9].extension[0].extension[2].valueInteger = 1
* group[0].element[9].display = "Diagnosis Identifier"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #diagnosis.condition(Condition.identifier)
* group[0].element[9].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[9].target.extension[0].extension[0].url = "type"
* group[0].element[9].target.extension[0].extension[0].valueCode = #"identifier"
* group[0].element[9].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[9].target.extension[0].extension[1].valueInteger = 0
* group[0].element[9].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[9].target.extension[0].extension[2].valueInteger = -1
* group[0].element[9].target.display = "diagnosis.condition(Condition.identifier)"
* group[0].element[9].target.comment = "We should confirm that this is truly a unique ID before it gets used as .id. It may need to be combined with a visit ID to make it fully unique."
* group[0].element[10].code = #DG1-21
* group[0].element[10].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[10].extension[0].extension[0].url = "type"
* group[0].element[10].extension[0].extension[0].valueCode = #"ID"
* group[0].element[10].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[10].extension[0].extension[1].valueInteger = 1
* group[0].element[10].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[10].extension[0].extension[2].valueInteger = 1
* group[0].element[10].display = "Diagnosis Action Code"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #diagnosis.condition(Condition.verificationStatus.coding.code)
* group[0].element[10].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[10].target.extension[0].extension[0].url = "type"
* group[0].element[10].target.extension[0].extension[0].valueCode = #"code"
* group[0].element[10].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[10].target.extension[0].extension[1].valueInteger = 0
* group[0].element[10].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[10].target.extension[0].extension[2].valueInteger = 1
* group[0].element[10].target.extension[0].extension[3].url = "assignment"
* group[0].element[10].target.extension[0].extension[3].valueString = "\"entered-in-error\""
* group[0].element[10].target.display = "diagnosis.condition(Condition.verificationStatus.coding.code)"
* group[0].element[10].target.comment = "Other values (A and U) don't map to anything"
* group[0].element[11].code = #DG1-21
* group[0].element[11].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[11].extension[0].extension[0].url = "type"
* group[0].element[11].extension[0].extension[0].valueCode = #"ID"
* group[0].element[11].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[11].extension[0].extension[1].valueInteger = 1
* group[0].element[11].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[11].extension[0].extension[2].valueInteger = 1
* group[0].element[11].display = "Diagnosis Action Code"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #diagnosis.condition(Condition.verificationStatus.coding.system)
* group[0].element[11].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[11].target.extension[0].extension[0].url = "type"
* group[0].element[11].target.extension[0].extension[0].valueCode = #"uri"
* group[0].element[11].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[11].target.extension[0].extension[1].valueInteger = 0
* group[0].element[11].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[11].target.extension[0].extension[2].valueInteger = 1
* group[0].element[11].target.extension[0].extension[3].url = "assignment"
* group[0].element[11].target.extension[0].extension[3].valueString = "\"http://terminology.hl7.org/CodeSystem/condition-ver-status\""
* group[0].element[11].target.display = "diagnosis.condition(Condition.verificationStatus.coding.system)"
* group[0].element[12].code = #DG1-22
* group[0].element[12].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[12].extension[0].extension[0].url = "type"
* group[0].element[12].extension[0].extension[0].valueCode = #"EI"
* group[0].element[12].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[12].extension[0].extension[1].valueInteger = 1
* group[0].element[12].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[12].extension[0].extension[2].valueInteger = 1
* group[0].element[12].display = "Parent Diagnosis"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #diagnosis.condition(Condition.extension[2].url)
* group[0].element[12].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[12].target.extension[0].extension[0].url = "assignment"
* group[0].element[12].target.extension[0].extension[0].valueString = "\"http://hl7.org/fhir/StructureDefinition/condition-dueTo\""
* group[0].element[12].target.display = "diagnosis.condition(Condition.extension[2].url)"
* group[0].element[13].code = #DG1-22
* group[0].element[13].extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[13].extension[0].extension[0].url = "type"
* group[0].element[13].extension[0].extension[0].valueCode = #"EI"
* group[0].element[13].extension[0].extension[1].url = "cardinalityMin"
* group[0].element[13].extension[0].extension[1].valueInteger = 1
* group[0].element[13].extension[0].extension[2].url = "cardinalityMax"
* group[0].element[13].extension[0].extension[2].valueInteger = 1
* group[0].element[13].display = "Parent Diagnosis"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #diagnosis.condition(Condition.extension[2].valueReference(Condition))
* group[0].element[13].target.extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/TypeInfo"
* group[0].element[13].target.extension[0].extension[0].url = "type"
* group[0].element[13].target.extension[0].extension[0].valueCode = #"Reference"
* group[0].element[13].target.extension[0].extension[1].url = "cardinalityMin"
* group[0].element[13].target.extension[0].extension[1].valueInteger = 0
* group[0].element[13].target.extension[0].extension[2].url = "cardinalityMax"
* group[0].element[13].target.extension[0].extension[2].valueInteger = 1
* group[0].element[13].target.display = "diagnosis.condition(Condition.extension[2].valueReference(Condition))"
* group[0].element[13].target.comment = "Extensions for occurredFollowing and related also exist"
