// HL7 Concept Map_ RepeatPattern - Sheet1.csv
Instance: TableHL70335ToV20335
InstanceOf: ConceptMap
Title: "Table HL70335 to V2 0335 Map"
Usage: #definition
* title = "Table HL70335 to V2 0335 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70335 to the FHIR V2 0335 Value Set."
* id = "table-hl70335-to-v2-0335"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70335-to-v2-0335"
* name = "TableHL70335ToV20335"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0335"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70335 to V2 0335.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1OBcSumRh0MVFA2C5YXcGsld9hxufvQWdhYINrTRvcWE/edit#gid=0"
* group[0].source = "http://terminology.hl7.org/CodeSystem/v2-0335"
* group[0].target = "http://terminology.hl7.org/CodeSystem/v2-0335"
* group[0].element[0].code = #Q<integer>S
* group[0].element[0].display = "every <integer> seconds"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #Q<integer>S
* group[0].element[0].target.display = "every <integer> seconds"
* group[0].element[1].code = #Q<integer>M
* group[0].element[1].display = "every <integer> minutes"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #Q<integer>M
* group[0].element[1].target.display = "every <integer> minutes"
* group[0].element[2].code = #Q<integer>H
* group[0].element[2].display = "every <integer> hours"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #Q<integer>H
* group[0].element[2].target.display = "every <integer> hours"
* group[0].element[3].code = #Q<integer>D
* group[0].element[3].display = "every <integer> days"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #Q<integer>D
* group[0].element[3].target.display = "every <integer> days"
* group[0].element[4].code = #Q<integer>W
* group[0].element[4].display = "every <integer> weeks"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #Q<integer>W
* group[0].element[4].target.display = "every <integer> weeks"
* group[0].element[5].code = #Q<integer>L
* group[0].element[5].display = "every <integer> months (Lunar cycle)"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #Q<integer>L
* group[0].element[5].target.display = "every <integer> months (Lunar cycle)"
* group[0].element[6].code = #Q<integer>J<day#>
* group[0].element[6].display = "repeats on a particular day of the week,"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #Q<integer>J<day#>
* group[0].element[6].target.display = "repeats on a particular day of the week,"
* group[0].element[7].code = #xID
* group[0].element[7].display = "\"X\" times per day at institution-specified times, where X is a numeral 5 or greater."
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #xID
* group[0].element[7].target.display = "\"X\" times per day at institution-specified times, where X is a numeral 5 or greater."
* group[0].element[8].code = #QAM
* group[0].element[8].display = "in the morning at institution-specified time"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #QAM
* group[0].element[8].target.display = "in the morning at institution-specified time"
* group[0].element[9].code = #QSHIFT
* group[0].element[9].display = "during each of three eight-hour shifts at institution-specified times"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #QSHIFT
* group[0].element[9].target.display = "during each of three eight-hour shifts at institution-specified times"
* group[0].element[10].code = #QHS
* group[0].element[10].display = "every day before the hour of sleep"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #QHS
* group[0].element[10].target.display = "every day before the hour of sleep"
* group[0].element[11].code = #QPM
* group[0].element[11].display = "in the evening at institution-specified time"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #QPM
* group[0].element[11].target.display = "in the evening at institution-specified time"
* group[0].element[12].code = #C
* group[0].element[12].display = "service is provided continuously between start time and stop time"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #C
* group[0].element[12].target.display = "service is provided continuously between start time and stop time"
* group[0].element[13].code = #"U <spec>"
* group[0].element[13].display = "for future use, where <spec> is an interval specification as defined by the UNIX cron specification."
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #"U <spec>"
* group[0].element[13].target.display = "for future use, where <spec> is an interval specification as defined by the UNIX cron specification."
* group[0].element[14].code = #PRN
* group[0].element[14].display = "given as needed"
* group[0].element[14].target.equivalence = #equivalent
* group[0].element[14].target.code = #PRN
* group[0].element[14].target.display = "given as needed"
* group[0].element[15].code = #PRNxxx
* group[0].element[15].display = "where xxx is some frequency code"
* group[0].element[15].target.equivalence = #equivalent
* group[0].element[15].target.code = #PRNxxx
* group[0].element[15].target.display = "where xxx is some frequency code"
* group[0].element[16].code = #Once
* group[0].element[16].display = "one time only."
* group[0].element[16].target.equivalence = #equivalent
* group[0].element[16].target.code = #Once
* group[0].element[16].target.display = "one time only."
* group[0].element[17].code = #"Meal Related Timings"
* group[0].element[17].display = "<timing>C (\"cum\")<meal>"
* group[0].element[17].target.equivalence = #equivalent
* group[0].element[17].target.code = #"Meal Related Timings"
* group[0].element[17].target.display = "<timing>C (\"cum\")<meal>"
* group[0].element[18].code = #A
* group[0].element[18].display = "Ante (before)"
* group[0].element[18].target.equivalence = #equivalent
* group[0].element[18].target.code = #A
* group[0].element[18].target.display = "Ante (before)"
* group[0].element[19].code = #P
* group[0].element[19].display = "Post (after)"
* group[0].element[19].target.equivalence = #equivalent
* group[0].element[19].target.code = #P
* group[0].element[19].target.display = "Post (after)"
* group[0].element[20].code = #I
* group[0].element[20].display = "Inter"
* group[0].element[20].target.equivalence = #equivalent
* group[0].element[20].target.code = #I
* group[0].element[20].target.display = "Inter"
* group[0].element[21].code = #M
* group[0].element[21].display = "Cibus Matutinus (breakfast)"
* group[0].element[21].target.equivalence = #equivalent
* group[0].element[21].target.code = #M
* group[0].element[21].target.display = "Cibus Matutinus (breakfast)"
* group[0].element[22].code = #D
* group[0].element[22].display = "Cibus Diurnus (lunch)"
* group[0].element[22].target.equivalence = #equivalent
* group[0].element[22].target.code = #D
* group[0].element[22].target.display = "Cibus Diurnus (lunch)"
* group[0].element[23].code = #V
* group[0].element[23].display = "Cibus Vespertinus (dinner)"
* group[0].element[23].target.equivalence = #equivalent
* group[0].element[23].target.code = #V
* group[0].element[23].target.display = "Cibus Vespertinus (dinner)"
* group[1].source = "http://terminology.hl7.org/CodeSystem/v2-0335"
* group[1].target = "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation"
* group[1].element[0].code = #BID
* group[1].element[0].display = "twice a day at institution-specified times"
* group[1].element[0].target.equivalence = #equivalent
* group[1].element[0].target.code = #BID
* group[1].element[0].target.display = "BID"
* group[1].element[1].code = #TID
* group[1].element[1].display = "three times a day at institution-specified times"
* group[1].element[1].target.equivalence = #equivalent
* group[1].element[1].target.code = #TID
* group[1].element[1].target.display = "TID"
* group[1].element[2].code = #QID
* group[1].element[2].display = "four times a day at institution-specified times"
* group[1].element[2].target.equivalence = #equivalent
* group[1].element[2].target.code = #QID
* group[1].element[2].target.display = "QID"
* group[1].element[3].code = #QOD
* group[1].element[3].display = "every other day"
* group[1].element[3].target.equivalence = #equivalent
* group[1].element[3].target.code = #QOD
* group[1].element[3].target.display = "QOD"
