// HL7 Concept Map_ ContactRole - Sheet1.csv
Instance: TableHL70131ToV20131
InstanceOf: ConceptMap
Title: "Table HL70131 to V2 0131 Map"
* title = "Table HL70131 to V2 0131 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70131 to the FHIR V2 0131 Value Set."
* id = "table-hl70131-to-v2-0131"
* url = "http://hl7.org/fhir/uv/v2mappings/table-hl70131-to-v2-0131"
* version = "1.0"
* name = "TableHL70131ToV20131"
* status = #active
* experimental = true
* date = "2023-12-04"
* publisher = "HL7 International, Inc"
* contact.telecom.system = #email
* contact.telecom.value = "v2-to-fhir@lists.hl7.org"
* copyright = "Copyright (c) 2020, HL7 International, Inc., All Rights Reserved."
* sourceUri = "HL70131"
* targetUri = "http://terminology.hl7.org/CodeSystem/v2-0131"
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70131 to V2 0131.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1IKIju2kedkokH5NGLWUlR1_Xsbdcplfb3wInd-W2lFE/edit#gid=0"
* group.element[0].code = #E
* group.element[0].display = "Employer"
* group.element[0].target.equivalence = #equivalent
* group.element[0].target.code = #E
* group.element[0].target.display = "Employer"
* group.element[1].code = #C
* group.element[1].display = "Emergency Contact"
* group.element[1].target.equivalence = #equivalent
* group.element[1].target.code = #C
* group.element[1].target.display = "Emergency Contact"
* group.element[2].code = #F
* group.element[2].display = "Federal Agency"
* group.element[2].target.equivalence = #equivalent
* group.element[2].target.code = #F
* group.element[2].target.display = "Federal Agency"
* group.element[3].code = #I
* group.element[3].display = "Insurance Company"
* group.element[3].target.equivalence = #equivalent
* group.element[3].target.code = #I
* group.element[3].target.display = "Insurance Company"
* group.element[4].code = #N
* group.element[4].display = "Next-of-Kin"
* group.element[4].target.equivalence = #equivalent
* group.element[4].target.code = #N
* group.element[4].target.display = "Next-of-Kin"
* group.element[5].code = #S
* group.element[5].display = "State Agency"
* group.element[5].target.equivalence = #equivalent
* group.element[5].target.code = #S
* group.element[5].target.display = "State Agency"
* group.element[6].code = #O
* group.element[6].display = "Other"
* group.element[6].target.equivalence = #equivalent
* group.element[6].target.code = #O
* group.element[6].target.display = "Other"
* group.element[7].code = #U
* group.element[7].display = "Unknown"
* group.element[7].target.equivalence = #equivalent
* group.element[7].target.code = #U
* group.element[7].target.display = "Unknown"
