// HL7 Concept Map_ AdditivePreservative - Sheet1.csv
Instance: TableHL70371ToV20371
InstanceOf: ConceptMap
Title: "Table HL70371 to V2 0371 Map"
* title = "Table HL70371 to V2 0371 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70371 to the FHIR V2 0371 Value Set."
* id = "table-hl70371-to-v2-0371"
* url = "http://hl7.org/fhir/uv/v2mappings/table-hl70371-to-v2-0371"
* version = "1.0"
* name = "TableHL70371ToV20371"
* status = #active
* experimental = true
* date = "2023-12-01"
* publisher = "HL7 International, Inc"
* contact.telecom.system = #email
* contact.telecom.value = "v2-to-fhir@lists.hl7.org"
* copyright = "Copyright (c) 2020, HL7 International, Inc., All Rights Reserved."
* sourceUri = "HL70371"
* targetUri = "http://terminology.hl7.org/CodeSystem/v2-0371"
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70371 to V2 0371.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1u8m8K-QMGTs7IT0nbw1jh4lGUH58XXmleONGkuxgOR0/edit#gid=0"
* group.element[0].code = #F10
* group.element[0].display = "10% Formalin"
* group.element[0].target.equivalence = #equivalent
* group.element[0].target.code = #F10
* group.element[0].target.display = "10% Formalin"
* group.element[1].code = #C32
* group.element[1].display = "3.2% Citrate"
* group.element[1].target.equivalence = #equivalent
* group.element[1].target.code = #C32
* group.element[1].target.display = "3.2% Citrate"
* group.element[2].code = #C38
* group.element[2].display = "3.8% Citrate"
* group.element[2].target.equivalence = #equivalent
* group.element[2].target.code = #C38
* group.element[2].target.display = "3.8% Citrate"
* group.element[3].code = #HCL6
* group.element[3].display = "6N HCL"
* group.element[3].target.equivalence = #equivalent
* group.element[3].target.code = #HCL6
* group.element[3].target.display = "6N HCL"
* group.element[4].code = #ACDA
* group.element[4].display = "ACD Solution A"
* group.element[4].target.equivalence = #equivalent
* group.element[4].target.code = #ACDA
* group.element[4].target.display = "ACD Solution A"
* group.element[5].code = #ACDB
* group.element[5].display = "ACD Solution B"
* group.element[5].target.equivalence = #equivalent
* group.element[5].target.code = #ACDB
* group.element[5].target.display = "ACD Solution B"
* group.element[6].code = #ACET
* group.element[6].display = "Acetic Acid"
* group.element[6].target.equivalence = #equivalent
* group.element[6].target.code = #ACET
* group.element[6].target.display = "Acetic Acid"
* group.element[7].code = #AMIES
* group.element[7].display = "Amies transport medium"
* group.element[7].target.equivalence = #equivalent
* group.element[7].target.code = #AMIES
* group.element[7].target.display = "Amies transport medium"
* group.element[8].code = #HEPA
* group.element[8].display = "Ammonium heparin"
* group.element[8].target.equivalence = #equivalent
* group.element[8].target.code = #HEPA
* group.element[8].target.display = "Ammonium heparin"
* group.element[9].code = #BACTM
* group.element[9].display = "Bacterial Transport medium"
* group.element[9].target.equivalence = #equivalent
* group.element[9].target.code = #BACTM
* group.element[9].target.display = "Bacterial Transport medium"
* group.element[10].code = #BOR
* group.element[10].display = "Borate Boric Acid"
* group.element[10].target.equivalence = #equivalent
* group.element[10].target.code = #BOR
* group.element[10].target.display = "Borate Boric Acid"
* group.element[11].code = #BOUIN
* group.element[11].display = "Bouin's solution"
* group.element[11].target.equivalence = #equivalent
* group.element[11].target.code = #BOUIN
* group.element[11].target.display = "Bouin's solution"
* group.element[12].code = #BF10
* group.element[12].display = "Buffered 10% formalin"
* group.element[12].target.equivalence = #equivalent
* group.element[12].target.code = #BF10
* group.element[12].target.display = "Buffered 10% formalin"
* group.element[13].code = #WEST
* group.element[13].display = "Buffered Citrate (Westergren Sedimentation Rate)"
* group.element[13].target.equivalence = #equivalent
* group.element[13].target.code = #WEST
* group.element[13].target.display = "Buffered Citrate (Westergren Sedimentation Rate)"
* group.element[14].code = #BSKM
* group.element[14].display = "Buffered skim milk"
* group.element[14].target.equivalence = #equivalent
* group.element[14].target.code = #BSKM
* group.element[14].target.display = "Buffered skim milk"
* group.element[15].code = #CARS
* group.element[15].display = "Carson's Modified 10% formalin"
* group.element[15].target.equivalence = #equivalent
* group.element[15].target.code = #CARS
* group.element[15].target.display = "Carson's Modified 10% formalin"
* group.element[16].code = #CARY
* group.element[16].display = "Cary Blair Medium"
* group.element[16].target.equivalence = #equivalent
* group.element[16].target.code = #CARY
* group.element[16].target.display = "Cary Blair Medium"
* group.element[17].code = #CHLTM
* group.element[17].display = "Chlamydia transport medium"
* group.element[17].target.equivalence = #equivalent
* group.element[17].target.code = #CHLTM
* group.element[17].target.display = "Chlamydia transport medium"
* group.element[18].code = #CTAD
* group.element[18].display = "CTAD (this should be spelled out if not universally understood)"
* group.element[18].target.equivalence = #equivalent
* group.element[18].target.code = #CTAD
* group.element[18].target.display = "CTAD (this should be spelled out if not universally understood)"
* group.element[19].code = #ENT
* group.element[19].display = "Enteric bacteria transport medium"
* group.element[19].target.equivalence = #equivalent
* group.element[19].target.code = #ENT
* group.element[19].target.display = "Enteric bacteria transport medium"
* group.element[20].code = #ENT+
* group.element[20].display = "Enteric plus"
* group.element[20].target.equivalence = #equivalent
* group.element[20].target.code = #ENT+
* group.element[20].target.display = "Enteric plus"
* group.element[21].code = #JKM
* group.element[21].display = "Jones Kendrick Medium"
* group.element[21].target.equivalence = #equivalent
* group.element[21].target.code = #JKM
* group.element[21].target.display = "Jones Kendrick Medium"
* group.element[22].code = #KARN
* group.element[22].display = "Karnovsky's fixative"
* group.element[22].target.equivalence = #equivalent
* group.element[22].target.code = #KARN
* group.element[22].target.display = "Karnovsky's fixative"
* group.element[23].code = #LIA
* group.element[23].display = "Lithium iodoacetate"
* group.element[23].target.equivalence = #equivalent
* group.element[23].target.code = #LIA
* group.element[23].target.display = "Lithium iodoacetate"
* group.element[24].code = #HEPL
* group.element[24].display = "Lithium/Li Heparin"
* group.element[24].target.equivalence = #equivalent
* group.element[24].target.code = #HEPL
* group.element[24].target.display = "Lithium/Li Heparin"
* group.element[25].code = #M4
* group.element[25].display = "M4"
* group.element[25].target.equivalence = #equivalent
* group.element[25].target.code = #M4
* group.element[25].target.display = "M4"
* group.element[26].code = #M4RT
* group.element[26].display = "M4-RT"
* group.element[26].target.equivalence = #equivalent
* group.element[26].target.code = #M4RT
* group.element[26].target.display = "M4-RT"
* group.element[27].code = #M5
* group.element[27].display = "M5"
* group.element[27].target.equivalence = #equivalent
* group.element[27].target.code = #M5
* group.element[27].target.display = "M5"
* group.element[28].code = #MICHTM
* group.element[28].display = "Michel's transport medium"
* group.element[28].target.equivalence = #equivalent
* group.element[28].target.code = #MICHTM
* group.element[28].target.display = "Michel's transport medium"
* group.element[29].code = #MMDTM
* group.element[29].display = "MMD transport medium"
* group.element[29].target.equivalence = #equivalent
* group.element[29].target.code = #MMDTM
* group.element[29].target.display = "MMD transport medium"
* group.element[30].code = #HNO3
* group.element[30].display = "Nitric Acid"
* group.element[30].target.equivalence = #equivalent
* group.element[30].target.code = #HNO3
* group.element[30].target.display = "Nitric Acid"
* group.element[31].code = #NONE
* group.element[31].display = "None"
* group.element[31].target.equivalence = #equivalent
* group.element[31].target.code = #NONE
* group.element[31].target.display = "None"
* group.element[32].code = #PAGE
* group.element[32].display = "Pages's Saline"
* group.element[32].target.equivalence = #equivalent
* group.element[32].target.code = #PAGE
* group.element[32].target.display = "Pages's Saline"
* group.element[33].code = #PHENOL
* group.element[33].display = "Phenol"
* group.element[33].target.equivalence = #equivalent
* group.element[33].target.code = #PHENOL
* group.element[33].target.display = "Phenol"
* group.element[34].code = #KOX
* group.element[34].display = "Potassium Oxalate"
* group.element[34].target.equivalence = #equivalent
* group.element[34].target.code = #KOX
* group.element[34].target.display = "Potassium Oxalate"
* group.element[35].code = #EDTK
* group.element[35].display = "Potassium/K EDTA"
* group.element[35].target.equivalence = #equivalent
* group.element[35].target.code = #EDTK
* group.element[35].target.display = "Potassium/K EDTA"
* group.element[36].code = #EDTK15
* group.element[36].display = "Potassium/K EDTA 15%"
* group.element[36].target.equivalence = #equivalent
* group.element[36].target.code = #EDTK15
* group.element[36].target.display = "Potassium/K EDTA 15%"
* group.element[37].code = #EDTK75
* group.element[37].display = "Potassium/K EDTA 7.5%"
* group.element[37].target.equivalence = #equivalent
* group.element[37].target.code = #EDTK75
* group.element[37].target.display = "Potassium/K EDTA 7.5%"
* group.element[38].code = #PVA
* group.element[38].display = "PVA (polyvinylalcohol)"
* group.element[38].target.equivalence = #equivalent
* group.element[38].target.code = #PVA
* group.element[38].target.display = "PVA (polyvinylalcohol)"
* group.element[39].code = #RLM
* group.element[39].display = "Reagan Lowe Medium"
* group.element[39].target.equivalence = #equivalent
* group.element[39].target.code = #RLM
* group.element[39].target.display = "Reagan Lowe Medium"
* group.element[40].code = #SST
* group.element[40].display = "Serum Separator Tube (Polymer Gel)"
* group.element[40].target.equivalence = #equivalent
* group.element[40].target.code = #SST
* group.element[40].target.display = "Serum Separator Tube (Polymer Gel)"
* group.element[41].code = #SILICA
* group.element[41].display = "Siliceous earth, 12 mg"
* group.element[41].target.equivalence = #equivalent
* group.element[41].target.code = #SILICA
* group.element[41].target.display = "Siliceous earth, 12 mg"
* group.element[42].code = #NAF
* group.element[42].display = "Sodium Fluoride"
* group.element[42].target.equivalence = #equivalent
* group.element[42].target.code = #NAF
* group.element[42].target.display = "Sodium Fluoride"
* group.element[43].code = #FL100
* group.element[43].display = "Sodium Fluoride, 100mg"
* group.element[43].target.equivalence = #equivalent
* group.element[43].target.code = #FL100
* group.element[43].target.display = "Sodium Fluoride, 100mg"
* group.element[44].code = #FL10
* group.element[44].display = "Sodium Fluoride, 10mg"
* group.element[44].target.equivalence = #equivalent
* group.element[44].target.code = #FL10
* group.element[44].target.display = "Sodium Fluoride, 10mg"
* group.element[45].code = #NAPS
* group.element[45].display = "Sodium polyanethol sulfonate 0.35% in 0.85% sodium chloride"
* group.element[45].target.equivalence = #equivalent
* group.element[45].target.code = #NAPS
* group.element[45].target.display = "Sodium polyanethol sulfonate 0.35% in 0.85% sodium chloride"
* group.element[46].code = #HEPN
* group.element[46].display = "Sodium/Na Heparin"
* group.element[46].target.equivalence = #equivalent
* group.element[46].target.code = #HEPN
* group.element[46].target.display = "Sodium/Na Heparin"
* group.element[47].code = #EDTN
* group.element[47].display = "Sodium/Na EDTA"
* group.element[47].target.equivalence = #equivalent
* group.element[47].target.code = #EDTN
* group.element[47].target.display = "Sodium/Na EDTA"
* group.element[48].code = #SPS
* group.element[48].display = "SPS(this should be spelled out if not universally understood)"
* group.element[48].target.equivalence = #equivalent
* group.element[48].target.code = #SPS
* group.element[48].target.display = "SPS(this should be spelled out if not universally understood)"
* group.element[49].code = #STUTM
* group.element[49].display = "Stuart transport medium"
* group.element[49].target.equivalence = #equivalent
* group.element[49].target.code = #STUTM
* group.element[49].target.display = "Stuart transport medium"
* group.element[50].code = #THROM
* group.element[50].display = "Thrombin"
* group.element[50].target.equivalence = #equivalent
* group.element[50].target.code = #THROM
* group.element[50].target.display = "Thrombin"
* group.element[51].code = #FDP
* group.element[51].display = "Thrombin NIH; soybean trypsin inhibitor (Fibrin Degradation Products)"
* group.element[51].target.equivalence = #equivalent
* group.element[51].target.code = #FDP
* group.element[51].target.display = "Thrombin NIH; soybean trypsin inhibitor (Fibrin Degradation Products)"
* group.element[52].code = #THYMOL
* group.element[52].display = "Thymol"
* group.element[52].target.equivalence = #equivalent
* group.element[52].target.code = #THYMOL
* group.element[52].target.display = "Thymol"
* group.element[53].code = #THYO
* group.element[53].display = "Thyoglycollate broth"
* group.element[53].target.equivalence = #equivalent
* group.element[53].target.code = #THYO
* group.element[53].target.display = "Thyoglycollate broth"
* group.element[54].code = #TOLU
* group.element[54].display = "Toluene"
* group.element[54].target.equivalence = #equivalent
* group.element[54].target.code = #TOLU
* group.element[54].target.display = "Toluene"
* group.element[55].code = #URETM
* group.element[55].display = "Ureaplasma transport medium"
* group.element[55].target.equivalence = #equivalent
* group.element[55].target.code = #URETM
* group.element[55].target.display = "Ureaplasma transport medium"
* group.element[56].code = #VIRTM
* group.element[56].display = "Viral Transport medium"
* group.element[56].target.equivalence = #equivalent
* group.element[56].target.code = #VIRTM
* group.element[56].target.display = "Viral Transport medium"
