// HL7 Concept Map_ EventRelatedPeriod - Sheet1.csv
Instance: TableHL70528ToV3TimingEvent
InstanceOf: ConceptMap
Title: "Table HL70528 to V3 TimingEvent Map"
Usage: #definition
* title = "Table HL70528 to V3 TimingEvent Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70528 to the FHIR V3 TimingEvent Value Set."
* id = "table-hl70528-to-v3-timingevent"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70528-to-v3-timingevent"
* name = "TableHL70528ToV3TimingEvent"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0528"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70528 to V3 TimingEvent.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/17o6vrrfJcGXA4EBuYcVhZs98dAJe5VS_TZ0LJYmVoTU/edit#gid=0"
* group[0].source = "http://terminology.hl7.org/CodeSystem/v2-0528"
* group[0].target = "http://terminology.hl7.org/CodeSystem/v3-TimingEvent"
* group[0].element[0].code = #HS
* group[0].element[0].display = "the hour of sleep (e.g., H18-22)"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #HS
* group[0].element[0].target.display = "HS"
* group[0].element[1].code = #AC
* group[0].element[1].display = "before meal (from lat. ante cibus)"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #AC
* group[0].element[1].target.display = "AC"
* group[0].element[2].code = #PC
* group[0].element[2].display = "after meal (from lat. post cibus)"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #PC
* group[0].element[2].target.display = "PC"
* group[0].element[3].code = #ACM
* group[0].element[3].display = "before breakfast (from lat. ante cibus matutinus)"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #ACM
* group[0].element[3].target.display = "ACM"
* group[0].element[4].code = #ACD
* group[0].element[4].display = "before lunch (from lat. ante cibus diurnus)"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #ACD
* group[0].element[4].target.display = "ACD"
* group[0].element[5].code = #ACV
* group[0].element[5].display = "before dinner (from lat. ante cibus vespertinus)"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #ACV
* group[0].element[5].target.display = "ACV"
* group[0].element[6].code = #PCM
* group[0].element[6].display = "after breakfast (from lat. post cibus matutinus)"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #PCM
* group[0].element[6].target.display = "PCM"
* group[0].element[7].code = #PCD
* group[0].element[7].display = "after lunch (from lat. post cibus diurnus)"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #PCD
* group[0].element[7].target.display = "PCD"
* group[0].element[8].code = #PCV
* group[0].element[8].display = "after dinner (from lat. post cibus vespertinus)"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #PCV
* group[0].element[8].target.display = "PCV"
* group[1].source = "http://terminology.hl7.org/CodeSystem/v2-0528"
* group[1].target = "http://terminology.hl7.org/CodeSystem/v2-0528"
* group[1].element[0].code = #IC
* group[1].element[0].display = "between meals (from lat. inter cibus)"
* group[1].element[0].target.equivalence = #equivalent
* group[1].element[0].target.code = #IC
* group[1].element[0].target.display = "between meals (from lat. inter cibus)"
* group[1].element[1].code = #ICM
* group[1].element[1].display = "between breakfast and lunch"
* group[1].element[1].target.equivalence = #equivalent
* group[1].element[1].target.code = #ICM
* group[1].element[1].target.display = "between breakfast and lunch"
* group[1].element[2].code = #ICD
* group[1].element[2].display = "between lunch and dinner"
* group[1].element[2].target.equivalence = #equivalent
* group[1].element[2].target.code = #ICD
* group[1].element[2].target.display = "between lunch and dinner"
* group[1].element[3].code = #ICV
* group[1].element[3].display = "between dinner and the hour of sleep"
* group[1].element[3].target.equivalence = #equivalent
* group[1].element[3].target.code = #ICV
* group[1].element[3].target.display = "between dinner and the hour of sleep"
