// HL7 Concept Map_ DegreeLicenseCertificate - Sheet1.csv
Instance: TableHL70360ToV20360
InstanceOf: ConceptMap
Title: "Table HL70360 to V2 0360 Map"
Usage: #definition
* title = "Table HL70360 to V2 0360 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70360 to the FHIR V2 0360 Value Set."
* id = "table-hl70360-to-v2-0360"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70360-to-v2-0360"
* name = "TableHL70360ToV20360"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0360"
* targetUri = "null"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70360 to V2 0360.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1hwElMvBeMgqshNl5Wm_YxToPC-szr8rCF90DT6h-Kzk/edit?gid=0#gid=0"
* group.element[0].code = #PN
* group.element[0].display = "Advanced Practice Nurse"
* group.element[0].target.equivalence = #equivalent
* group.element[0].target.code = #PN
* group.element[0].target.display = "Advanced Practice Nurse"
* group.element[1].code = #AAS
* group.element[1].display = "Associate of Applied Science"
* group.element[1].target.equivalence = #equivalent
* group.element[1].target.code = #AAS
* group.element[1].target.display = "Associate of Applied Science"
* group.element[2].code = #AA
* group.element[2].display = "Associate of Arts"
* group.element[2].target.equivalence = #equivalent
* group.element[2].target.code = #AA
* group.element[2].target.display = "Associate of Arts"
* group.element[3].code = #ABA
* group.element[3].display = "Associate of Business Administration"
* group.element[3].target.equivalence = #equivalent
* group.element[3].target.code = #ABA
* group.element[3].target.display = "Associate of Business Administration"
* group.element[4].code = #AE
* group.element[4].display = "Associate of Engineering"
* group.element[4].target.equivalence = #equivalent
* group.element[4].target.code = #AE
* group.element[4].target.display = "Associate of Engineering"
* group.element[5].code = #AS
* group.element[5].display = "Associate of Science"
* group.element[5].target.equivalence = #equivalent
* group.element[5].target.code = #AS
* group.element[5].target.display = "Associate of Science"
* group.element[6].code = #BA
* group.element[6].display = "Bachelor of Arts"
* group.element[6].target.equivalence = #equivalent
* group.element[6].target.code = #BA
* group.element[6].target.display = "Bachelor of Arts"
* group.element[7].code = #BBA
* group.element[7].display = "Bachelor of Business Administration"
* group.element[7].target.equivalence = #equivalent
* group.element[7].target.code = #BBA
* group.element[7].target.display = "Bachelor of Business Administration"
* group.element[8].code = #BE
* group.element[8].display = "Bachelor or Engineering"
* group.element[8].target.equivalence = #equivalent
* group.element[8].target.code = #BE
* group.element[8].target.display = "Bachelor or Engineering"
* group.element[9].code = #BFA
* group.element[9].display = "Bachelor of Fine Arts"
* group.element[9].target.equivalence = #equivalent
* group.element[9].target.code = #BFA
* group.element[9].target.display = "Bachelor of Fine Arts"
* group.element[10].code = #BN
* group.element[10].display = "Bachelor of Nursing"
* group.element[10].target.equivalence = #equivalent
* group.element[10].target.code = #BN
* group.element[10].target.display = "Bachelor of Nursing"
* group.element[11].code = #BS
* group.element[11].display = "Bachelor of Science"
* group.element[11].target.equivalence = #equivalent
* group.element[11].target.code = #BS
* group.element[11].target.display = "Bachelor of Science"
* group.element[12].code = #BSL
* group.element[12].display = "Bachelor of Science - Law"
* group.element[12].target.equivalence = #equivalent
* group.element[12].target.code = #BSL
* group.element[12].target.display = "Bachelor of Science - Law"
* group.element[13].code = #BSN
* group.element[13].display = "Bachelor on Science - Nursing"
* group.element[13].target.equivalence = #equivalent
* group.element[13].target.code = #BSN
* group.element[13].target.display = "Bachelor on Science - Nursing"
* group.element[14].code = #BT
* group.element[14].display = "Bachelor of Theology"
* group.element[14].target.equivalence = #equivalent
* group.element[14].target.code = #BT
* group.element[14].target.display = "Bachelor of Theology"
* group.element[15].code = #CER
* group.element[15].display = "Certificate"
* group.element[15].target.equivalence = #equivalent
* group.element[15].target.code = #CER
* group.element[15].target.display = "Certificate"
* group.element[16].code = #CANP
* group.element[16].display = "Certified Adult Nurse Practitioner"
* group.element[16].target.equivalence = #equivalent
* group.element[16].target.code = #CANP
* group.element[16].target.display = "Certified Adult Nurse Practitioner"
* group.element[17].code = #CMA
* group.element[17].display = "Certified Medical Assistant"
* group.element[17].target.equivalence = #equivalent
* group.element[17].target.code = #CMA
* group.element[17].target.display = "Certified Medical Assistant"
* group.element[18].code = #CNP
* group.element[18].display = "Certified Nurse Practitioner"
* group.element[18].target.equivalence = #equivalent
* group.element[18].target.code = #CNP
* group.element[18].target.display = "Certified Nurse Practitioner"
* group.element[19].code = #CNM
* group.element[19].display = "Certified Nurse Midwife"
* group.element[19].target.equivalence = #equivalent
* group.element[19].target.code = #CNM
* group.element[19].target.display = "Certified Nurse Midwife"
* group.element[20].code = #CRN
* group.element[20].display = "Certified Registered Nurse"
* group.element[20].target.equivalence = #equivalent
* group.element[20].target.code = #CRN
* group.element[20].target.display = "Certified Registered Nurse"
* group.element[21].code = #CNS
* group.element[21].display = "Certified Nurse Specialist"
* group.element[21].target.equivalence = #equivalent
* group.element[21].target.code = #CNS
* group.element[21].target.display = "Certified Nurse Specialist"
* group.element[22].code = #CPNP
* group.element[22].display = "Certified Pediatric Nurse Practitioner"
* group.element[22].target.equivalence = #equivalent
* group.element[22].target.code = #CPNP
* group.element[22].target.display = "Certified Pediatric Nurse Practitioner"
* group.element[23].code = #CTR
* group.element[23].display = "Certified Tumor Registrar"
* group.element[23].target.equivalence = #equivalent
* group.element[23].target.code = #CTR
* group.element[23].target.display = "Certified Tumor Registrar"
* group.element[24].code = #DIP
* group.element[24].display = "Diploma"
* group.element[24].target.equivalence = #equivalent
* group.element[24].target.code = #DIP
* group.element[24].target.display = "Diploma"
* group.element[25].code = #DBA
* group.element[25].display = "Doctor of Business Administration"
* group.element[25].target.equivalence = #equivalent
* group.element[25].target.code = #DBA
* group.element[25].target.display = "Doctor of Business Administration"
* group.element[26].code = #DED
* group.element[26].display = "Doctor of Education"
* group.element[26].target.equivalence = #equivalent
* group.element[26].target.code = #DED
* group.element[26].target.display = "Doctor of Education"
* group.element[27].code = #PharmD
* group.element[27].display = "Doctor of Pharmacy"
* group.element[27].target.equivalence = #equivalent
* group.element[27].target.code = #PharmD
* group.element[27].target.display = "Doctor of Pharmacy"
* group.element[28].code = #PHE
* group.element[28].display = "Doctor of Engineering"
* group.element[28].target.equivalence = #equivalent
* group.element[28].target.code = #PHE
* group.element[28].target.display = "Doctor of Engineering"
* group.element[29].code = #PHD
* group.element[29].display = "Doctor of Philosophy"
* group.element[29].target.equivalence = #equivalent
* group.element[29].target.code = #PHD
* group.element[29].target.display = "Doctor of Philosophy"
* group.element[30].code = #PHS
* group.element[30].display = "Doctor of Science"
* group.element[30].target.equivalence = #equivalent
* group.element[30].target.code = #PHS
* group.element[30].target.display = "Doctor of Science"
* group.element[31].code = #MD
* group.element[31].display = "Doctor of Medicine"
* group.element[31].target.equivalence = #equivalent
* group.element[31].target.code = #MD
* group.element[31].target.display = "Doctor of Medicine"
* group.element[32].code = #DO
* group.element[32].display = "Doctor of Osteopathy"
* group.element[32].target.equivalence = #equivalent
* group.element[32].target.code = #DO
* group.element[32].target.display = "Doctor of Osteopathy"
* group.element[33].code = #EMT
* group.element[33].display = "Emergency Medical Technician"
* group.element[33].target.equivalence = #equivalent
* group.element[33].target.code = #EMT
* group.element[33].target.display = "Emergency Medical Technician"
* group.element[34].code = #EMTP
* group.element[34].display = "Emergency Medical Technician - Paramedic"
* group.element[34].target.equivalence = #equivalent
* group.element[34].target.code = #EMTP
* group.element[34].target.display = "Emergency Medical Technician - Paramedic"
* group.element[35].code = #FPNP
* group.element[35].display = "Family Practice Nurse Practitioner"
* group.element[35].target.equivalence = #equivalent
* group.element[35].target.code = #FPNP
* group.element[35].target.display = "Family Practice Nurse Practitioner"
* group.element[36].code = #HS
* group.element[36].display = "High School Graduate"
* group.element[36].target.equivalence = #equivalent
* group.element[36].target.code = #HS
* group.element[36].target.display = "High School Graduate"
* group.element[37].code = #JD
* group.element[37].display = "Juris Doctor"
* group.element[37].target.equivalence = #equivalent
* group.element[37].target.code = #JD
* group.element[37].target.display = "Juris Doctor"
* group.element[38].code = #MA
* group.element[38].display = "Master of Arts"
* group.element[38].target.equivalence = #equivalent
* group.element[38].target.code = #MA
* group.element[38].target.display = "Master of Arts"
* group.element[39].code = #MBA
* group.element[39].display = "Master of Business Administration"
* group.element[39].target.equivalence = #equivalent
* group.element[39].target.code = #MBA
* group.element[39].target.display = "Master of Business Administration"
* group.element[40].code = #MCE
* group.element[40].display = "Master of Civil Engineering"
* group.element[40].target.equivalence = #equivalent
* group.element[40].target.code = #MCE
* group.element[40].target.display = "Master of Civil Engineering"
* group.element[41].code = #MDI
* group.element[41].display = "Master of Divinity"
* group.element[41].target.equivalence = #equivalent
* group.element[41].target.code = #MDI
* group.element[41].target.display = "Master of Divinity"
* group.element[42].code = #MED
* group.element[42].display = "Master of Education"
* group.element[42].target.equivalence = #equivalent
* group.element[42].target.code = #MED
* group.element[42].target.display = "Master of Education"
* group.element[43].code = #MEE
* group.element[43].display = "Master of Electrical Engineering"
* group.element[43].target.equivalence = #equivalent
* group.element[43].target.code = #MEE
* group.element[43].target.display = "Master of Electrical Engineering"
* group.element[44].code = #ME
* group.element[44].display = "Master of Engineering"
* group.element[44].target.equivalence = #equivalent
* group.element[44].target.code = #ME
* group.element[44].target.display = "Master of Engineering"
* group.element[45].code = #MFA
* group.element[45].display = "Master of Fine Arts"
* group.element[45].target.equivalence = #equivalent
* group.element[45].target.code = #MFA
* group.element[45].target.display = "Master of Fine Arts"
* group.element[46].code = #MME
* group.element[46].display = "Master of Mechanical Engineering"
* group.element[46].target.equivalence = #equivalent
* group.element[46].target.code = #MME
* group.element[46].target.display = "Master of Mechanical Engineering"
* group.element[47].code = #MS
* group.element[47].display = "Master of Science"
* group.element[47].target.equivalence = #equivalent
* group.element[47].target.code = #MS
* group.element[47].target.display = "Master of Science"
* group.element[48].code = #MSL
* group.element[48].display = "Master of Science - Law"
* group.element[48].target.equivalence = #equivalent
* group.element[48].target.code = #MSL
* group.element[48].target.display = "Master of Science - Law"
* group.element[49].code = #MSN
* group.element[49].display = "Master of Science - Nursing"
* group.element[49].target.equivalence = #equivalent
* group.element[49].target.code = #MSN
* group.element[49].target.display = "Master of Science - Nursing"
* group.element[50].code = #MTH
* group.element[50].display = "Master of Theology"
* group.element[50].target.equivalence = #equivalent
* group.element[50].target.code = #MTH
* group.element[50].target.display = "Master of Theology"
* group.element[51].code = #MDA
* group.element[51].display = "Medical Assistant"
* group.element[51].target.equivalence = #equivalent
* group.element[51].target.code = #MDA
* group.element[51].target.display = "Medical Assistant"
* group.element[52].code = #MT
* group.element[52].display = "Medical Technician"
* group.element[52].target.equivalence = #equivalent
* group.element[52].target.code = #MT
* group.element[52].target.display = "Medical Technician"
* group.element[53].code = #NG
* group.element[53].display = "Non-Graduate"
* group.element[53].target.equivalence = #equivalent
* group.element[53].target.code = #NG
* group.element[53].target.display = "Non-Graduate"
* group.element[54].code = #NP
* group.element[54].display = "Nurse Practitioner"
* group.element[54].target.equivalence = #equivalent
* group.element[54].target.code = #NP
* group.element[54].target.display = "Nurse Practitioner"
* group.element[55].code = #PA
* group.element[55].display = "Physician Assistant"
* group.element[55].target.equivalence = #equivalent
* group.element[55].target.code = #PA
* group.element[55].target.display = "Physician Assistant"
* group.element[56].code = #RMA
* group.element[56].display = "Registered Medical Assistant"
* group.element[56].target.equivalence = #equivalent
* group.element[56].target.code = #RMA
* group.element[56].target.display = "Registered Medical Assistant"
* group.element[57].code = #RN
* group.element[57].display = "Registered Nurse"
* group.element[57].target.equivalence = #equivalent
* group.element[57].target.code = #RN
* group.element[57].target.display = "Registered Nurse"
* group.element[58].code = #RPH
* group.element[58].display = "Registered Pharmacist"
* group.element[58].target.equivalence = #equivalent
* group.element[58].target.code = #RPH
* group.element[58].target.display = "Registered Pharmacist"
* group.element[59].code = #SEC
* group.element[59].display = "Secretarial Certificate"
* group.element[59].target.equivalence = #equivalent
* group.element[59].target.code = #SEC
* group.element[59].target.display = "Secretarial Certificate"
* group.element[60].code = #TS
* group.element[60].display = "Trade School Graduate"
* group.element[60].target.equivalence = #equivalent
* group.element[60].target.code = #TS
* group.element[60].target.display = "Trade School Graduate"
