// HL7 Concept Map_ DiagnosticServiceSectionID - Sheet1.csv
Instance: TableHL70074ToV20074
InstanceOf: ConceptMap
Title: "Table HL70074 to V2 0074 Map"
Usage: #definition
* title = "Table HL70074 to V2 0074 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70074 to the FHIR V2 0074 Value Set."
* id = "table-hl70074-to-v2-0074"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70074-to-v2-0074"
* name = "TableHL70074ToV20074"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0074"
* targetUri = "http://terminology.hl7.org/ValueSet/v2-0074"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70074 to V2 0074.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/190IK3DXu5_bpGgesA5ZZ_YxN009gyutbuT5yztzB3BI/edit#gid=0"
* group[0].source = "http://terminology.hl7.org/CodeSystem/v2-0074"
* group[0].target = "http://terminology.hl7.org/CodeSystem/v2-0074"
* group[0].element[0].code = #AU
* group[0].element[0].display = "Audiology"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #AU
* group[0].element[0].target.display = "Audiology"
* group[0].element[1].code = #BG
* group[0].element[1].display = "Blood Gases"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #BG
* group[0].element[1].target.display = "Blood Gases"
* group[0].element[2].code = #BLB
* group[0].element[2].display = "Blood Bank"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #BLB
* group[0].element[2].target.display = "Blood Bank"
* group[0].element[3].code = #CG
* group[0].element[3].display = "Cytogenetics"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #CG
* group[0].element[3].target.display = "Cytogenetics"
* group[0].element[4].code = #CUS
* group[0].element[4].display = "Cardiac Ultrasound"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #CUS
* group[0].element[4].target.display = "Cardiac Ultrasound"
* group[0].element[5].code = #CTH
* group[0].element[5].display = "Cardiac Catheterization"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #CTH
* group[0].element[5].target.display = "Cardiac Catheterization"
* group[0].element[6].code = #CT
* group[0].element[6].display = "CAT Scan"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #CT
* group[0].element[6].target.display = "CAT Scan"
* group[0].element[7].code = #CH
* group[0].element[7].display = "Chemistry"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #CH
* group[0].element[7].target.display = "Chemistry"
* group[0].element[8].code = #CP
* group[0].element[8].display = "Cytopathology"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #CP
* group[0].element[8].target.display = "Cytopathology"
* group[0].element[9].code = #EC
* group[0].element[9].display = "Electrocardiac (e.g., EKG,  EEC, Holter)"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #EC
* group[0].element[9].target.display = "Electrocardiac (e.g., EKG,  EEC, Holter)"
* group[0].element[10].code = #EN
* group[0].element[10].display = "Electroneuro (EEG, EMG,EP,PSG)"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #EN
* group[0].element[10].target.display = "Electroneuro (EEG, EMG,EP,PSG)"
* group[0].element[11].code = #GE
* group[0].element[11].display = "Genetics"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #GE
* group[0].element[11].target.display = "Genetics"
* group[0].element[12].code = #HM
* group[0].element[12].display = "Hematology"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #HM
* group[0].element[12].target.display = "Hematology"
* group[0].element[13].code = #ICU
* group[0].element[13].display = "Bedside ICU Monitoring"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #ICU
* group[0].element[13].target.display = "Bedside ICU Monitoring"
* group[0].element[14].code = #IMM
* group[0].element[14].display = "Immunology"
* group[0].element[14].target.equivalence = #equivalent
* group[0].element[14].target.code = #IMM
* group[0].element[14].target.display = "Immunology"
* group[0].element[15].code = #LAB
* group[0].element[15].display = "Laboratory"
* group[0].element[15].target.equivalence = #equivalent
* group[0].element[15].target.code = #LAB
* group[0].element[15].target.display = "Laboratory"
* group[0].element[16].code = #MB
* group[0].element[16].display = "Microbiology"
* group[0].element[16].target.equivalence = #equivalent
* group[0].element[16].target.code = #MB
* group[0].element[16].target.display = "Microbiology"
* group[0].element[17].code = #MCB
* group[0].element[17].display = "Mycobacteriology"
* group[0].element[17].target.equivalence = #equivalent
* group[0].element[17].target.code = #MCB
* group[0].element[17].target.display = "Mycobacteriology"
* group[0].element[18].code = #MYC
* group[0].element[18].display = "Mycology"
* group[0].element[18].target.equivalence = #equivalent
* group[0].element[18].target.code = #MYC
* group[0].element[18].target.display = "Mycology"
* group[0].element[19].code = #NMS
* group[0].element[19].display = "Nuclear Medicine Scan"
* group[0].element[19].target.equivalence = #equivalent
* group[0].element[19].target.code = #NMS
* group[0].element[19].target.display = "Nuclear Medicine Scan"
* group[0].element[20].code = #NMR
* group[0].element[20].display = "Nuclear Magnetic Resonance"
* group[0].element[20].target.equivalence = #equivalent
* group[0].element[20].target.code = #NMR
* group[0].element[20].target.display = "Nuclear Magnetic Resonance"
* group[0].element[21].code = #NRS
* group[0].element[21].display = "Nursing Service Measures"
* group[0].element[21].target.equivalence = #equivalent
* group[0].element[21].target.code = #NRS
* group[0].element[21].target.display = "Nursing Service Measures"
* group[0].element[22].code = #OUS
* group[0].element[22].display = "OB Ultrasound"
* group[0].element[22].target.equivalence = #equivalent
* group[0].element[22].target.code = #OUS
* group[0].element[22].target.display = "OB Ultrasound"
* group[0].element[23].code = #OT
* group[0].element[23].display = "Occupational Therapy"
* group[0].element[23].target.equivalence = #equivalent
* group[0].element[23].target.code = #OT
* group[0].element[23].target.display = "Occupational Therapy"
* group[0].element[24].code = #OTH
* group[0].element[24].display = "Other"
* group[0].element[24].target.equivalence = #equivalent
* group[0].element[24].target.code = #OTH
* group[0].element[24].target.display = "Other"
* group[0].element[25].code = #OSL
* group[0].element[25].display = "Outside Lab"
* group[0].element[25].target.equivalence = #equivalent
* group[0].element[25].target.code = #OSL
* group[0].element[25].target.display = "Outside Lab"
* group[0].element[26].code = #PHR
* group[0].element[26].display = "Pharmacy"
* group[0].element[26].target.equivalence = #equivalent
* group[0].element[26].target.code = #PHR
* group[0].element[26].target.display = "Pharmacy"
* group[0].element[27].code = #PT
* group[0].element[27].display = "Physical Therapy"
* group[0].element[27].target.equivalence = #equivalent
* group[0].element[27].target.code = #PT
* group[0].element[27].target.display = "Physical Therapy"
* group[0].element[28].code = #PHY
* group[0].element[28].display = "Physician (Hx. Dx, admission note, etc.)"
* group[0].element[28].target.equivalence = #equivalent
* group[0].element[28].target.code = #PHY
* group[0].element[28].target.display = "Physician (Hx. Dx, admission note, etc.)"
* group[0].element[29].code = #PF
* group[0].element[29].display = "Pulmonary Function"
* group[0].element[29].target.equivalence = #equivalent
* group[0].element[29].target.code = #PF
* group[0].element[29].target.display = "Pulmonary Function"
* group[0].element[30].code = #RAD
* group[0].element[30].display = "Radiology"
* group[0].element[30].target.equivalence = #equivalent
* group[0].element[30].target.code = #RAD
* group[0].element[30].target.display = "Radiology"
* group[0].element[31].code = #RX
* group[0].element[31].display = "Radiograph"
* group[0].element[31].target.equivalence = #equivalent
* group[0].element[31].target.code = #RX
* group[0].element[31].target.display = "Radiograph"
* group[0].element[32].code = #RUS
* group[0].element[32].display = "Radiology Ultrasound"
* group[0].element[32].target.equivalence = #equivalent
* group[0].element[32].target.code = #RUS
* group[0].element[32].target.display = "Radiology Ultrasound"
* group[0].element[33].code = #RC
* group[0].element[33].display = "Respiratory Care (therapy)"
* group[0].element[33].target.equivalence = #equivalent
* group[0].element[33].target.code = #RC
* group[0].element[33].target.display = "Respiratory Care (therapy)"
* group[0].element[34].code = #RT
* group[0].element[34].display = "Radiation Therapy"
* group[0].element[34].target.equivalence = #equivalent
* group[0].element[34].target.code = #RT
* group[0].element[34].target.display = "Radiation Therapy"
* group[0].element[35].code = #SR
* group[0].element[35].display = "Serology"
* group[0].element[35].target.equivalence = #equivalent
* group[0].element[35].target.code = #SR
* group[0].element[35].target.display = "Serology"
* group[0].element[36].code = #SP
* group[0].element[36].display = "Surgical Pathology"
* group[0].element[36].target.equivalence = #equivalent
* group[0].element[36].target.code = #SP
* group[0].element[36].target.display = "Surgical Pathology"
* group[0].element[37].code = #TX
* group[0].element[37].display = "Toxicology"
* group[0].element[37].target.equivalence = #equivalent
* group[0].element[37].target.code = #TX
* group[0].element[37].target.display = "Toxicology"
* group[0].element[38].code = #VUS
* group[0].element[38].display = "Vascular Ultrasound"
* group[0].element[38].target.equivalence = #equivalent
* group[0].element[38].target.code = #VUS
* group[0].element[38].target.display = "Vascular Ultrasound"
* group[0].element[39].code = #VR
* group[0].element[39].display = "Virology"
* group[0].element[39].target.equivalence = #equivalent
* group[0].element[39].target.code = #VR
* group[0].element[39].target.display = "Virology"
* group[0].element[40].code = #XRC
* group[0].element[40].display = "Cineradiograph"
* group[0].element[40].target.equivalence = #equivalent
* group[0].element[40].target.code = #XRC
* group[0].element[40].target.display = "Cineradiograph"
