// HL7 Concept Map_ OrderControlCode[ServiceRequest.status] - Sheet1.csv
Instance: TableHL70119ToRequestStatus
InstanceOf: ConceptMap
Title: "Table HL70119 to Request Status Map"
Usage: #definition
* title = "Table HL70119 to Request Status Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70119 to the FHIR Request Status Value Set."
* id = "table-hl70119-to-request-status"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70119-to-request-status"
* name = "TableHL70119ToRequestStatus"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0119"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70119 to Request Status.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1-M3ehfvgrNyOwWBIP3--KMEN6A0vi90W-hnkdrUIYIg/edit#gid=0"
* group[0].source = "http://terminology.hl7.org/CodeSystem/v2-0119"
* group[0].target = "http://hl7.org/fhir/request-status"
* group[0].element[0].code = #AF
* group[0].element[0].display = "Order/service refill request approval"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #active
* group[0].element[0].target.display = "Active"
* group[0].element[1].code = #CA
* group[0].element[1].display = "Cancel order/service request"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #active
* group[0].element[1].target.display = "Active"
* group[0].element[2].code = #CR
* group[0].element[2].display = "Canceled as requested"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #revoked
* group[0].element[2].target.display = "Revoked"
* group[0].element[3].code = #DC
* group[0].element[3].display = "Discontinue order/service request"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #revoked
* group[0].element[3].target.display = "Revoked"
* group[0].element[4].code = #DF
* group[0].element[4].display = "Order/service refill request denied"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #revoked
* group[0].element[4].target.display = "Revoked"
* group[0].element[5].code = #DR
* group[0].element[5].display = "Discontinued as requested"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #revoked
* group[0].element[5].target.display = "Revoked"
* group[0].element[6].code = #FU
* group[0].element[6].display = "Order/service refilled, unsolicited"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #completed
* group[0].element[6].target.display = "Completed"
* group[0].element[7].code = #HD
* group[0].element[7].display = "Hold order request"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #active
* group[0].element[7].target.display = "Active"
* group[0].element[8].code = #HR
* group[0].element[8].display = "On hold as requested"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #on-hold
* group[0].element[8].target.display = "On Hold"
* group[0].element[9].code = #NW
* group[0].element[9].display = "New order/Service"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #active
* group[0].element[9].target.display = "Active"
* group[0].element[10].code = #OC
* group[0].element[10].display = "Order/service canceled"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #revoked
* group[0].element[10].target.display = "Revoked"
* group[0].element[11].code = #OD
* group[0].element[11].display = "Order/service discontinued"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #revoked
* group[0].element[11].target.display = "Revoked"
* group[0].element[12].code = #OH
* group[0].element[12].display = "Order/service held"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #on-hold
* group[0].element[12].target.display = "On Hold"
* group[0].element[13].code = #OK
* group[0].element[13].display = "Order/service accepted & OK"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #active
* group[0].element[13].target.display = "Active"
* group[0].element[14].code = #PR
* group[0].element[14].display = "Previous Results with new order/service"
* group[0].element[14].target.equivalence = #equivalent
* group[0].element[14].target.code = #active
* group[0].element[14].target.display = "Active"
* group[0].element[15].code = #PY
* group[0].element[15].display = "Notification of replacement order for outside dispense"
* group[0].element[15].target.equivalence = #equivalent
* group[0].element[15].target.code = #active
* group[0].element[15].target.display = "Active"
* group[0].element[16].code = #RL
* group[0].element[16].display = "Release previous hold"
* group[0].element[16].target.equivalence = #equivalent
* group[0].element[16].target.code = #active
* group[0].element[16].target.display = "Active"
* group[0].element[17].code = #RO
* group[0].element[17].display = "Replacement order"
* group[0].element[17].target.equivalence = #equivalent
* group[0].element[17].target.code = #active
* group[0].element[17].target.display = "Active"
* group[0].element[18].code = #RQ
* group[0].element[18].display = "Replaced as requested"
* group[0].element[18].target.equivalence = #equivalent
* group[0].element[18].target.code = #active
* group[0].element[18].target.display = "Active"
* group[1].source = "http://terminology.hl7.org/CodeSystem/v2-0119"
* group[1].element[0].code = #CH
* group[1].element[0].display = "Child order/service"
* group[1].element[0].target.equivalence = #unmatched
* group[1].element[1].code = #CN
* group[1].element[1].display = "Combined result"
* group[1].element[1].target.equivalence = #unmatched
* group[1].element[2].code = #CP
* group[1].element[2].display = "Cancel process step"
* group[1].element[2].target.equivalence = #unmatched
* group[1].element[3].code = #DE
* group[1].element[3].display = "Data errors"
* group[1].element[3].target.equivalence = #unmatched
* group[1].element[4].code = #LI
* group[1].element[4].display = "Link order/service to patient care problem or goal"
* group[1].element[4].target.equivalence = #unmatched
* group[1].element[5].code = #NA
* group[1].element[5].display = "Number assigned"
* group[1].element[5].target.equivalence = #unmatched
* group[1].element[6].code = #OE
* group[1].element[6].display = "Order/service released"
* group[1].element[6].target.equivalence = #unmatched
* group[1].element[7].code = #OF
* group[1].element[7].display = "Order/service refilled as requested"
* group[1].element[7].target.equivalence = #unmatched
* group[1].element[8].code = #OP
* group[1].element[8].display = "Notification of order for outside dispense"
* group[1].element[8].target.equivalence = #unmatched
* group[1].element[9].code = #OR
* group[1].element[9].display = "Released as requested"
* group[1].element[9].target.equivalence = #unmatched
* group[1].element[10].code = #PA
* group[1].element[10].display = "Parent order/service"
* group[1].element[10].target.equivalence = #unmatched
* group[1].element[11].code = #RE
* group[1].element[11].display = "Observations/Performed Service to follow"
* group[1].element[11].target.equivalence = #unmatched
* group[1].element[12].code = #RF
* group[1].element[12].display = "Refill order/service request"
* group[1].element[12].target.equivalence = #unmatched
* group[1].element[13].code = #RP
* group[1].element[13].display = "Order/service replace request"
* group[1].element[13].target.equivalence = #unmatched
* group[1].element[14].code = #RR
* group[1].element[14].display = "Request received"
* group[1].element[14].target.equivalence = #unmatched
* group[1].element[15].code = #RU
* group[1].element[15].display = "Replaced unsolicited"
* group[1].element[15].target.equivalence = #unmatched
* group[1].element[16].code = #SC
* group[1].element[16].display = "Status changed"
* group[1].element[16].target.equivalence = #unmatched
* group[1].element[17].code = #SN
* group[1].element[17].display = "Send order/service number"
* group[1].element[17].target.equivalence = #unmatched
* group[1].element[18].code = #SR
* group[1].element[18].display = "Response to send order/service status request"
* group[1].element[18].target.equivalence = #unmatched
* group[1].element[19].code = #SS
* group[1].element[19].display = "Send order/service status request"
* group[1].element[19].target.equivalence = #unmatched
* group[1].element[20].code = #UA
* group[1].element[20].display = "Unable to accept order/service"
* group[1].element[20].target.equivalence = #unmatched
* group[1].element[21].code = #UC
* group[1].element[21].display = "Unable to cancel"
* group[1].element[21].target.equivalence = #unmatched
* group[1].element[22].code = #UD
* group[1].element[22].display = "Unable to discontinue"
* group[1].element[22].target.equivalence = #unmatched
* group[1].element[23].code = #UF
* group[1].element[23].display = "Unable to refill"
* group[1].element[23].target.equivalence = #unmatched
* group[1].element[24].code = #UH
* group[1].element[24].display = "Unable to put on hold"
* group[1].element[24].target.equivalence = #unmatched
* group[1].element[25].code = #UM
* group[1].element[25].display = "Unable to replace"
* group[1].element[25].target.equivalence = #unmatched
* group[1].element[26].code = #UN
* group[1].element[26].display = "Unlink order/service from patient care problem or goal"
* group[1].element[26].target.equivalence = #unmatched
* group[1].element[27].code = #UR
* group[1].element[27].display = "Unable to release"
* group[1].element[27].target.equivalence = #unmatched
* group[1].element[28].code = #UX
* group[1].element[28].display = "Unable to change"
* group[1].element[28].target.equivalence = #unmatched
* group[1].element[29].code = #XO
* group[1].element[29].display = "Change order/service request"
* group[1].element[29].target.equivalence = #unmatched
* group[1].element[30].code = #XR
* group[1].element[30].display = "Changed as requested"
* group[1].element[30].target.equivalence = #unmatched
* group[1].element[31].code = #XX
* group[1].element[31].display = "Order/service changed, unsol."
* group[1].element[31].target.equivalence = #unmatched
* group[1].element[32].code = #MC
* group[1].element[32].display = "Miscellaneous Charge – not associated with an order"
* group[1].element[32].target.equivalence = #unmatched
