// HL7 Concept Map_ Participation - Sheet1.csv
Instance: TableHL70912ToPractitionerRole
InstanceOf: ConceptMap
Title: "Table HL70912 to Practitioner Role Map"
Usage: #definition
* title = "Table HL70912 to Practitioner Role Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70912 to the FHIR Practitioner Role Value Set."
* id = "table-hl70912-to-practitioner-role"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70912-to-practitioner-role"
* name = "TableHL70912ToPractitionerRole"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0912"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70912 to Practitioner Role.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1rbjK6-XxY2BoCpVRWy_Mrvkl9PTk_8zw0GIeng8zz-4/edit#gid=0"
* group[0].source = "http://terminology.hl7.org/CodeSystem/v2-0912"
* group[0].target = "http://terminology.hl7.org/CodeSystem/practitioner-role"
* group[0].element[0].code = #PH
* group[0].element[0].display = "Pharmacist"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #pharmacist
* group[0].element[0].target.display = "Pharmacist"
* group[1].source = "http://terminology.hl7.org/CodeSystem/v2-0912"
* group[1].element[0].code = #AAP
* group[1].element[0].display = "Alert Acknowledging Provider"
* group[1].element[0].target.equivalence = #unmatched
* group[1].element[1].code = #AC
* group[1].element[1].display = "Administration Cosigner"
* group[1].element[1].target.equivalence = #unmatched
* group[1].element[2].code = #AD
* group[1].element[2].display = "Admitting Provider"
* group[1].element[2].target.equivalence = #unmatched
* group[1].element[3].code = #AI
* group[1].element[3].display = "Assistant/Alternate Interpreter"
* group[1].element[3].target.equivalence = #unmatched
* group[1].element[4].code = #AP
* group[1].element[4].display = "Administering Provider"
* group[1].element[4].target.equivalence = #unmatched
* group[1].element[5].code = #ARI
* group[1].element[5].display = "Assistant Result Interpreter"
* group[1].element[5].target.equivalence = #unmatched
* group[1].element[6].code = #AT
* group[1].element[6].display = "Attending Provider"
* group[1].element[6].target.equivalence = #unmatched
* group[1].element[7].code = #AUT
* group[1].element[7].display = "Author/Event Initiator"
* group[1].element[7].target.equivalence = #unmatched
* group[1].element[8].code = #CP
* group[1].element[8].display = "Consulting Provider"
* group[1].element[8].target.equivalence = #unmatched
* group[1].element[9].code = #DP
* group[1].element[9].display = "Dispensing Provider"
* group[1].element[9].target.equivalence = #unmatched
* group[1].element[10].code = #EP
* group[1].element[10].display = "Entering Person"
* group[1].element[10].target.equivalence = #unmatched
* group[1].element[11].code = #EQUIP
* group[1].element[11].display = "Equipment"
* group[1].element[11].target.equivalence = #unmatched
* group[1].element[12].code = #FHCP
* group[1].element[12].display = "Family Health Care Professional"
* group[1].element[12].target.equivalence = #unmatched
* group[1].element[13].code = #MDIR
* group[1].element[13].display = "Medical Director"
* group[1].element[13].target.equivalence = #unmatched
* group[1].element[14].code = #OP
* group[1].element[14].display = "Ordering Provider"
* group[1].element[14].target.equivalence = #unmatched
* group[1].element[15].code = #OS
* group[1].element[15].display = "Outside Site(s) Where Observation May Be Performed"
* group[1].element[15].target.equivalence = #unmatched
* group[1].element[16].code = #PB
* group[1].element[16].display = "Packed by"
* group[1].element[16].target.equivalence = #unmatched
* group[1].element[17].code = #PI
* group[1].element[17].display = "Primary Interpreter"
* group[1].element[17].target.equivalence = #unmatched
* group[1].element[18].code = #PO
* group[1].element[18].display = "Performing Organization"
* group[1].element[18].target.equivalence = #unmatched
* group[1].element[19].code = #POMD
* group[1].element[19].display = "Performing Organization Medical Director"
* group[1].element[19].target.equivalence = #unmatched
* group[1].element[20].code = #PP
* group[1].element[20].display = "Primary Care Provider"
* group[1].element[20].target.equivalence = #unmatched
* group[1].element[21].code = #PRI
* group[1].element[21].display = "Principal Result Interpreter"
* group[1].element[21].target.equivalence = #unmatched
* group[1].element[22].code = #RCT
* group[1].element[22].display = "Results Copies To"
* group[1].element[22].target.equivalence = #unmatched
* group[1].element[23].code = #RO
* group[1].element[23].display = "Responsible Observer"
* group[1].element[23].target.equivalence = #unmatched
* group[1].element[24].code = #RP
* group[1].element[24].display = "Referring Provider"
* group[1].element[24].target.equivalence = #unmatched
* group[1].element[25].code = #RT
* group[1].element[25].display = "Referred to Provider"
* group[1].element[25].target.equivalence = #unmatched
* group[1].element[26].code = #SB
* group[1].element[26].display = "Send by"
* group[1].element[26].target.equivalence = #unmatched
* group[1].element[27].code = #SC
* group[1].element[27].display = "Specimen Collector"
* group[1].element[27].target.equivalence = #unmatched
* group[1].element[28].code = #TN
* group[1].element[28].display = "Technician"
* group[1].element[28].target.equivalence = #unmatched
* group[1].element[29].code = #TR
* group[1].element[29].display = "Transcriptionist"
* group[1].element[29].target.equivalence = #unmatched
* group[1].element[30].code = #VP
* group[1].element[30].display = "Verifier (Verifying Person)"
* group[1].element[30].target.equivalence = #unmatched
* group[1].element[31].code = #VPS
* group[1].element[31].display = "Verifying Pharmaceutical Supplier   (not sure how to dissect Pharmacist/Treatment Supplier's Verifier ID)"
* group[1].element[31].target.equivalence = #unmatched
* group[1].element[32].code = #VTS
* group[1].element[32].display = "Verifying Treatment Supplier   (not sure how to dissect Pharmacist/Treatment Supplier's Verifier ID)"
* group[1].element[32].target.equivalence = #unmatched
* group[1].element[33].code = #WAY
* group[1].element[33].display = "Waypoint"
* group[1].element[33].target.equivalence = #unmatched
* group[1].element[34].code = #WAYR
* group[1].element[34].display = "Waypoint Recipient"
* group[1].element[34].target.equivalence = #unmatched
