// HL7 Concept Map_ SpecimenRejectReason - Sheet1.csv
Instance: TableHL70490ToV20490
InstanceOf: ConceptMap
Title: "Table HL70490 to V2 0490 Map"
Usage: #definition
* title = "Table HL70490 to V2 0490 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70490 to the FHIR V2 0490 Value Set."
* id = "table-hl70490-to-v2-0490"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70490-to-v2-0490"
* name = "TableHL70490ToV20490"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0490"
* targetUri = "http://terminology.hl7.org/ValueSet/v2-0490"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70490 to V2 0490.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1r1-CV9pi_ravlxzhSjB97bDs4Jp0HSOa8r_2-0UuMGg/edit#gid=0"
* group[0].source = "http://terminology.hl7.org/CodeSystem/v2-0490"
* group[0].target = "http://terminology.hl7.org/CodeSystem/v2-0490"
* group[0].element[0].code = #EX
* group[0].element[0].display = "Expired"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #EX
* group[0].element[0].target.display = "Expired"
* group[0].element[1].code = #QS
* group[0].element[1].display = "Quantity not sufficient"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #QS
* group[0].element[1].target.display = "Quantity not sufficient"
* group[0].element[2].code = #RB
* group[0].element[2].display = "Broken container"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #RB
* group[0].element[2].target.display = "Broken container"
* group[0].element[3].code = #RC
* group[0].element[3].display = "Clotting"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #RC
* group[0].element[3].target.display = "Clotting"
* group[0].element[4].code = #RD
* group[0].element[4].display = "Missing collection date"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #RD
* group[0].element[4].target.display = "Missing collection date"
* group[0].element[5].code = #RA
* group[0].element[5].display = "Missing patient ID number"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #RA
* group[0].element[5].target.display = "Missing patient ID number"
* group[0].element[6].code = #RE
* group[0].element[6].display = "Missing patient name"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #RE
* group[0].element[6].target.display = "Missing patient name"
* group[0].element[7].code = #RH
* group[0].element[7].display = "Hemolysis"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #RH
* group[0].element[7].target.display = "Hemolysis"
* group[0].element[8].code = #RI
* group[0].element[8].display = "Identification problem"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #RI
* group[0].element[8].target.display = "Identification problem"
* group[0].element[9].code = #RM
* group[0].element[9].display = "Labeling"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #RM
* group[0].element[9].target.display = "Labeling"
* group[0].element[10].code = #RN
* group[0].element[10].display = "Contamination"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #RN
* group[0].element[10].target.display = "Contamination"
* group[0].element[11].code = #RP
* group[0].element[11].display = "Missing phlebotomist ID"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #RP
* group[0].element[11].target.display = "Missing phlebotomist ID"
* group[0].element[12].code = #RR
* group[0].element[12].display = "Improper storage"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #RR
* group[0].element[12].target.display = "Improper storage"
* group[0].element[13].code = #RS
* group[0].element[13].display = "Name misspelling"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #RS
* group[0].element[13].target.display = "Name misspelling"
