// HL7 Concept Map_ RepeatPattern - Sheet1.csv
Instance: TableHL70335ToV20335
InstanceOf: ConceptMap
Title: "Table HL70335null to V2 0335 Map"
* title = "Table HL70335null to V2 0335 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70335 to the FHIR V2 0335 Value Set."
* id = "table-hl70335-to-v2-0335"
* url = "http://hl7.org/fhir/uv/v2mappings/table-hl70335-to-v2-0335"
* version = "1.0"
* name = "TableHL70335ToV20335"
* status = #active
* experimental = true
* date = "2024-10-14"
* publisher = "HL7 International, Inc"
* contact.telecom.system = #email
* contact.telecom.value = "v2-to-fhir@lists.hl7.org"
* copyright = "Copyright (c) 2020, HL7 International, Inc., All Rights Reserved."
* sourceUri = "HL70335"
* targetUri = "http://terminology.hl7.org/CodeSystem/v2-0335"
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70335 to V2 0335.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1OBcSumRh0MVFA2C5YXcGsld9hxufvQWdhYINrTRvcWE/edit#gid=0"
* group.element[0].code = #Q<integer>S
* group.element[0].display = "every <integer> seconds"
* group.element[0].target.equivalence = #equivalent
* group.element[0].target.code = #Q<integer>S
* group.element[0].target.display = "every <integer> seconds"
* group.element[1].code = #Q<integer>M
* group.element[1].display = "every <integer> minutes"
* group.element[1].target.equivalence = #equivalent
* group.element[1].target.code = #Q<integer>M
* group.element[1].target.display = "every <integer> minutes"
* group.element[2].code = #Q<integer>H
* group.element[2].display = "every <integer> hours"
* group.element[2].target.equivalence = #equivalent
* group.element[2].target.code = #Q<integer>H
* group.element[2].target.display = "every <integer> hours"
* group.element[3].code = #Q1H
* group.element[3].display = "every 1 hours"
* group.element[3].target.equivalence = #equivalent
* group.element[3].target.code = #Q1H
* group.element[3].target.display = "every hour"
* group.element[4].code = #Q2H
* group.element[4].display = "every 2 hours"
* group.element[4].target.equivalence = #equivalent
* group.element[4].target.code = #Q2H
* group.element[4].target.display = "every 2 hours"
* group.element[5].code = #Q3H
* group.element[5].display = "every 3 hours"
* group.element[5].target.equivalence = #equivalent
* group.element[5].target.code = #Q3H
* group.element[5].target.display = "every 3 hours"
* group.element[6].code = #Q4H
* group.element[6].display = "every 4 hours"
* group.element[6].target.equivalence = #equivalent
* group.element[6].target.code = #Q4H
* group.element[6].target.display = "Q4H"
* group.element[7].code = #Q6H
* group.element[7].display = "every 6 hours"
* group.element[7].target.equivalence = #equivalent
* group.element[7].target.code = #Q6H
* group.element[7].target.display = "Q6H"
* group.element[8].code = #Q8H
* group.element[8].display = "every 8 hours"
* group.element[8].target.equivalence = #equivalent
* group.element[8].target.code = #Q8H
* group.element[8].target.display = "every 8 hours"
* group.element[9].code = #Q<integer>D
* group.element[9].display = "every <integer> days"
* group.element[9].target.equivalence = #equivalent
* group.element[9].target.code = #Q<integer>D
* group.element[9].target.display = "every <integer> days"
* group.element[10].code = #Q1D
* group.element[10].display = "every 1 days"
* group.element[10].target.equivalence = #equivalent
* group.element[10].target.code = #QD
* group.element[10].target.display = "QD"
* group.element[11].code = #Q<integer>W
* group.element[11].display = "every <integer> weeks"
* group.element[11].target.equivalence = #equivalent
* group.element[11].target.code = #Q<integer>W
* group.element[11].target.display = "every <integer> weeks"
* group.element[12].code = #Q1W
* group.element[12].display = "every 1 weeks"
* group.element[12].target.equivalence = #equivalent
* group.element[12].target.code = #WK
* group.element[12].target.display = "weekly"
* group.element[13].code = #Q<integer>L
* group.element[13].display = "every <integer> months (Lunar cycle)"
* group.element[13].target.equivalence = #equivalent
* group.element[13].target.code = #Q<integer>L
* group.element[13].target.display = "every <integer> months (Lunar cycle)"
* group.element[14].code = #Q1L
* group.element[14].display = "every 1 months (Lunar)"
* group.element[14].target.equivalence = #equivalent
* group.element[14].target.code = #MO
* group.element[14].target.display = "monthly"
* group.element[15].code = #Q<integer>J<day#>
* group.element[15].display = "repeats on a particular day of the week,"
* group.element[15].target.equivalence = #equivalent
* group.element[15].target.code = #Q<integer>J<day#>
* group.element[15].target.display = "repeats on a particular day of the week,"
* group.element[16].code = #BID
* group.element[16].display = "twice a day at institution-specified times"
* group.element[16].target.equivalence = #equivalent
* group.element[16].target.code = #BID
* group.element[16].target.display = "BID"
* group.element[17].code = #TID
* group.element[17].display = "three times a day at institution-specified times"
* group.element[17].target.equivalence = #equivalent
* group.element[17].target.code = #TID
* group.element[17].target.display = "TID"
* group.element[18].code = #QID
* group.element[18].display = "four times a day at institution-specified times"
* group.element[18].target.equivalence = #equivalent
* group.element[18].target.code = #QID
* group.element[18].target.display = "QID"
* group.element[19].code = #xID
* group.element[19].display = "\"X\" times per day at institution-specified times, where X is a numeral 5 or greater."
* group.element[19].target.equivalence = #equivalent
* group.element[19].target.code = #xID
* group.element[19].target.display = "\"X\" times per day at institution-specified times, where X is a numeral 5 or greater."
* group.element[20].code = #QAM
* group.element[20].display = "in the morning at institution-specified time"
* group.element[20].target.equivalence = #equivalent
* group.element[20].target.code = #QAM
* group.element[20].target.display = "in the morning at institution-specified time"
* group.element[21].code = #QSHIFT
* group.element[21].display = "during each of three eight-hour shifts at institution-specified times"
* group.element[21].target.equivalence = #equivalent
* group.element[21].target.code = #QSHIFT
* group.element[21].target.display = "during each of three eight-hour shifts at institution-specified times"
* group.element[22].code = #QOD
* group.element[22].display = "every other day"
* group.element[22].target.equivalence = #equivalent
* group.element[22].target.code = #QOD
* group.element[22].target.display = "QOD"
* group.element[23].code = #QHS
* group.element[23].display = "every day before the hour of sleep"
* group.element[23].target.equivalence = #equivalent
* group.element[23].target.code = #QHS
* group.element[23].target.display = "every day before the hour of sleep"
* group.element[24].code = #QPM
* group.element[24].display = "in the evening at institution-specified time"
* group.element[24].target.equivalence = #equivalent
* group.element[24].target.code = #QPM
* group.element[24].target.display = "in the evening at institution-specified time"
* group.element[25].code = #C
* group.element[25].display = "service is provided continuously between start time and stop time"
* group.element[25].target.equivalence = #equivalent
* group.element[25].target.code = #C
* group.element[25].target.display = "service is provided continuously between start time and stop time"
* group.element[26].code = #U<spec>
* group.element[26].display = "for future use, where <spec> is an interval specification as defined by the UNIX cron specification."
* group.element[26].target.equivalence = #equivalent
* group.element[26].target.code = #U
* group.element[26].target.display = "for future use, where <spec> is an interval specification as defined by the UNIX cron specification."
* group.element[26].target.comment = "<spec>."
* group.element[27].code = #PRN
* group.element[27].display = "given as needed"
* group.element[27].target.equivalence = #equivalent
* group.element[27].target.code = #PRN
* group.element[27].target.display = "given as needed"
* group.element[28].code = #PRNxxx
* group.element[28].display = "where xxx is some frequency code"
* group.element[28].target.equivalence = #equivalent
* group.element[28].target.code = #PRNxxx
* group.element[28].target.display = "where xxx is some frequency code"
* group.element[29].code = #Once
* group.element[29].display = "one time only."
* group.element[29].target.equivalence = #equivalent
* group.element[29].target.code = #Once
* group.element[29].target.display = "one time only."
* group.element[30].code = #Meal_Related_Timings
* group.element[30].display = "<timing>C (\"cum\")<meal>"
* group.element[30].target.equivalence = #equivalent
* group.element[30].target.code = #Meal
* group.element[30].target.display = "<timing>C (\"cum\")<meal>"
* group.element[30].target.comment = "Related Timings."
* group.element[31].code = #A
* group.element[31].display = "Ante (before)"
* group.element[31].target.equivalence = #equivalent
* group.element[31].target.code = #A
* group.element[31].target.display = "Ante (before)"
* group.element[32].code = #P
* group.element[32].display = "Post (after)"
* group.element[32].target.equivalence = #equivalent
* group.element[32].target.code = #P
* group.element[32].target.display = "Post (after)"
* group.element[33].code = #I
* group.element[33].display = "Inter"
* group.element[33].target.equivalence = #equivalent
* group.element[33].target.code = #I
* group.element[33].target.display = "Inter"
* group.element[34].code = #M
* group.element[34].display = "Cibus Matutinus (breakfast)"
* group.element[34].target.equivalence = #equivalent
* group.element[34].target.code = #M
* group.element[34].target.display = "Cibus Matutinus (breakfast)"
* group.element[35].code = #D
* group.element[35].display = "Cibus Diurnus (lunch)"
* group.element[35].target.equivalence = #equivalent
* group.element[35].target.code = #D
* group.element[35].target.display = "Cibus Diurnus (lunch)"
* group.element[36].code = #V
* group.element[36].display = "Cibus Vespertinus (dinner)"
* group.element[36].target.equivalence = #equivalent
* group.element[36].target.code = #V
* group.element[36].target.display = "Cibus Vespertinus (dinner)"
