// HL7 Concept Map_ UniversalIDType - Sheet1.csv
Instance: TableHL70301ToV20301
InstanceOf: ConceptMap
Title: "Table HL70301 to V2 0301 Map"
Usage: #definition
* title = "Table HL70301 to V2 0301 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70301 to the FHIR V2 0301 Value Set."
* id = "table-hl70301-to-v2-0301"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70301-to-v2-0301"
* name = "TableHL70301ToV20301"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0301"
* targetUri = "http://terminology.hl7.org/ValueSet/v2-0301"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70301 to V2 0301.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1YC0HqPfyRswWwvWh_9iHaTECvY8m2vk4DjYl0K56pc0/edit#gid=0"
* group[0].source = "http://terminology.hl7.org/CodeSystem/v2-0301"
* group[0].target = "http://terminology.hl7.org/CodeSystem/v2-0301"
* group[0].element[0].code = #DNS
* group[0].element[0].display = "Domain Name System"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #DNS
* group[0].element[0].target.display = "Domain Name System"
* group[0].element[1].code = #EUI64
* group[0].element[1].display = "IEEE 64-bit Extended Unique Identifier"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #EUI64
* group[0].element[1].target.display = "IEEE 64-bit Extended Unique Identifier"
* group[0].element[2].code = #CLIA
* group[0].element[2].display = "Clinical Laboratory Improvement Amendments"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #CLIA
* group[0].element[2].target.display = "Clinical Laboratory Improvement Amendments"
* group[0].element[3].code = #CLIP
* group[0].element[3].display = "Clinical laboratory Improvement Program"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #CLIP
* group[0].element[3].target.display = "Clinical laboratory Improvement Program"
* group[0].element[4].code = #GUID
* group[0].element[4].display = "globally unique identifier"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #GUID
* group[0].element[4].target.display = "globally unique identifier"
* group[0].element[5].code = #HCD
* group[0].element[5].display = "CEN Healthcare Coding Identifier"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #HCD
* group[0].element[5].target.display = "CEN Healthcare Coding Identifier"
* group[0].element[6].code = #HL7
* group[0].element[6].display = "HL7 registration schemes"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #HL7
* group[0].element[6].target.display = "HL7 registration schemes"
* group[0].element[7].code = #ISO
* group[0].element[7].display = "ISO Object Identifier"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #ISO
* group[0].element[7].target.display = "ISO Object Identifier"
* group[0].element[8].code = #L,M,N
* group[0].element[8].display = "Local"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #L
* group[0].element[8].target.display = "Local"
* group[0].element[8].target.comment = ",M,N."
* group[0].element[9].code = #Random
* group[0].element[9].display = "Random"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #Random
* group[0].element[9].target.display = "Random"
* group[0].element[10].code = #URI
* group[0].element[10].display = "Uniform Resource Identifier"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #URI
* group[0].element[10].target.display = "Uniform Resource Identifier"
* group[0].element[11].code = #UUID
* group[0].element[11].display = "Universal Unique Identifier"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #UUID
* group[0].element[11].target.display = "Universal Unique Identifier"
* group[0].element[12].code = #x400
* group[0].element[12].display = "X.400 MHS identifier"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #x400
* group[0].element[12].target.display = "X.400 MHS identifier"
* group[0].element[13].code = #x500
* group[0].element[13].display = "X500 directory Name"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #x500
* group[0].element[13].target.display = "X500 directory Name"
