// HL7 Concept Map_ BodySite - Sheet1.csv
Instance: TableHL70163ToV20163
InstanceOf: ConceptMap
Title: "Table HL70163 to V2 0163 Map"
Usage: #definition
* title = "Table HL70163 to V2 0163 Map"
* description = "This ConceptMap represents a mapping from the HL7 V2 Table HL70163 to the FHIR V2 0163 Value Set."
* id = "table-hl70163-to-v2-0163"
* url = "http://hl7.org/fhir/uv/v2mappings/ConceptMap/table-hl70163-to-v2-0163"
* name = "TableHL70163ToV20163"
* sourceUri = "http://terminology.hl7.org/ValueSet/v2-0163"
* targetUri = "http://terminology.hl7.org/ValueSet/v2-0163"
* insert PublicationData
* extension[0].url = "http://hl7.org/fhir/uv/v2mappings/StructureDefinition/RelatedArtifact"
* extension[0].extension[0].url = "type"
* extension[0].extension[0].valueCode = #derived-from
* extension[0].extension[1].url = "label"
* extension[0].extension[1].valueString = "Table HL70163 to V2 0163.fsh"
* extension[0].extension[2].url = "url"
* extension[0].extension[2].valueUri = "https://docs.google.com/spreadsheets/d/1Bk09POJ7Iqb9oozYAJJEUEnHZwnmH15kHbtCvbbpixc/edit?gid=0#gid=0"
* group[0].source = "http://terminology.hl7.org/CodeSystem/v2-0163"
* group[0].target = "http://terminology.hl7.org/CodeSystem/v2-0163"
* group[0].element[0].code = #BE
* group[0].element[0].display = "Bilateral Ears"
* group[0].element[0].target.equivalence = #equivalent
* group[0].element[0].target.code = #BE
* group[0].element[0].target.display = "Bilateral Ears"
* group[0].element[1].code = #OU
* group[0].element[1].display = "Bilateral Eyes"
* group[0].element[1].target.equivalence = #equivalent
* group[0].element[1].target.code = #OU
* group[0].element[1].target.display = "Bilateral Eyes"
* group[0].element[2].code = #BN
* group[0].element[2].display = "Bilateral Nares"
* group[0].element[2].target.equivalence = #equivalent
* group[0].element[2].target.code = #BN
* group[0].element[2].target.display = "Bilateral Nares"
* group[0].element[3].code = #BU
* group[0].element[3].display = "Buttock"
* group[0].element[3].target.equivalence = #equivalent
* group[0].element[3].target.code = #BU
* group[0].element[3].target.display = "Buttock"
* group[0].element[4].code = #CT
* group[0].element[4].display = "Chest Tube"
* group[0].element[4].target.equivalence = #equivalent
* group[0].element[4].target.code = #CT
* group[0].element[4].target.display = "Chest Tube"
* group[0].element[5].code = #LA
* group[0].element[5].display = "Left Arm"
* group[0].element[5].target.equivalence = #equivalent
* group[0].element[5].target.code = #LA
* group[0].element[5].target.display = "Left Arm"
* group[0].element[6].code = #LAC
* group[0].element[6].display = "Left Anterior Chest"
* group[0].element[6].target.equivalence = #equivalent
* group[0].element[6].target.code = #LAC
* group[0].element[6].target.display = "Left Anterior Chest"
* group[0].element[7].code = #LACF
* group[0].element[7].display = "Left Antecubital Fossa"
* group[0].element[7].target.equivalence = #equivalent
* group[0].element[7].target.code = #LACF
* group[0].element[7].target.display = "Left Antecubital Fossa"
* group[0].element[8].code = #LD
* group[0].element[8].display = "Left Deltoid"
* group[0].element[8].target.equivalence = #equivalent
* group[0].element[8].target.code = #LD
* group[0].element[8].target.display = "Left Deltoid"
* group[0].element[9].code = #LE
* group[0].element[9].display = "Left Ear"
* group[0].element[9].target.equivalence = #equivalent
* group[0].element[9].target.code = #LE
* group[0].element[9].target.display = "Left Ear"
* group[0].element[10].code = #LEJ
* group[0].element[10].display = "Left External Jugular"
* group[0].element[10].target.equivalence = #equivalent
* group[0].element[10].target.code = #LEJ
* group[0].element[10].target.display = "Left External Jugular"
* group[0].element[11].code = #OS
* group[0].element[11].display = "Left Eye"
* group[0].element[11].target.equivalence = #equivalent
* group[0].element[11].target.code = #OS
* group[0].element[11].target.display = "Left Eye"
* group[0].element[12].code = #LF
* group[0].element[12].display = "Left Foot"
* group[0].element[12].target.equivalence = #equivalent
* group[0].element[12].target.code = #LF
* group[0].element[12].target.display = "Left Foot"
* group[0].element[13].code = #LG
* group[0].element[13].display = "Left Gluteus Medius"
* group[0].element[13].target.equivalence = #equivalent
* group[0].element[13].target.code = #LG
* group[0].element[13].target.display = "Left Gluteus Medius"
* group[0].element[14].code = #LH
* group[0].element[14].display = "Left Hand"
* group[0].element[14].target.equivalence = #equivalent
* group[0].element[14].target.code = #LH
* group[0].element[14].target.display = "Left Hand"
* group[0].element[15].code = #LIJ
* group[0].element[15].display = "Left Internal Jugular"
* group[0].element[15].target.equivalence = #equivalent
* group[0].element[15].target.code = #LIJ
* group[0].element[15].target.display = "Left Internal Jugular"
* group[0].element[16].code = #LLAQ
* group[0].element[16].display = "Left Lower Abd Quadrant"
* group[0].element[16].target.equivalence = #equivalent
* group[0].element[16].target.code = #LLAQ
* group[0].element[16].target.display = "Left Lower Abd Quadrant"
* group[0].element[17].code = #LLFA
* group[0].element[17].display = "Left Lower Forearm"
* group[0].element[17].target.equivalence = #equivalent
* group[0].element[17].target.code = #LLFA
* group[0].element[17].target.display = "Left Lower Forearm"
* group[0].element[18].code = #LMFA
* group[0].element[18].display = "Left Mid Forearm"
* group[0].element[18].target.equivalence = #equivalent
* group[0].element[18].target.code = #LMFA
* group[0].element[18].target.display = "Left Mid Forearm"
* group[0].element[19].code = #LN
* group[0].element[19].display = "Left Naris"
* group[0].element[19].target.equivalence = #equivalent
* group[0].element[19].target.code = #LN
* group[0].element[19].target.display = "Left Naris"
* group[0].element[20].code = #LPC
* group[0].element[20].display = "Left Posterior Chest"
* group[0].element[20].target.equivalence = #equivalent
* group[0].element[20].target.code = #LPC
* group[0].element[20].target.display = "Left Posterior Chest"
* group[0].element[21].code = #LSC
* group[0].element[21].display = "Left Subclavian"
* group[0].element[21].target.equivalence = #equivalent
* group[0].element[21].target.code = #LSC
* group[0].element[21].target.display = "Left Subclavian"
* group[0].element[22].code = #LT
* group[0].element[22].display = "Left Thigh"
* group[0].element[22].target.equivalence = #equivalent
* group[0].element[22].target.code = #LT
* group[0].element[22].target.display = "Left Thigh"
* group[0].element[23].code = #LUA
* group[0].element[23].display = "Left Upper Arm"
* group[0].element[23].target.equivalence = #equivalent
* group[0].element[23].target.code = #LUA
* group[0].element[23].target.display = "Left Upper Arm"
* group[0].element[24].code = #LUAQ
* group[0].element[24].display = "Left Upper Abd Quadrant"
* group[0].element[24].target.equivalence = #equivalent
* group[0].element[24].target.code = #LUAQ
* group[0].element[24].target.display = "Left Upper Abd Quadrant"
* group[0].element[25].code = #LUFA
* group[0].element[25].display = "Left Upper Forearm"
* group[0].element[25].target.equivalence = #equivalent
* group[0].element[25].target.code = #LUFA
* group[0].element[25].target.display = "Left Upper Forearm"
* group[0].element[26].code = #LVG
* group[0].element[26].display = "Left Ventragluteal"
* group[0].element[26].target.equivalence = #equivalent
* group[0].element[26].target.code = #LVG
* group[0].element[26].target.display = "Left Ventragluteal"
* group[0].element[27].code = #LVL
* group[0].element[27].display = "Left Vastus Lateralis"
* group[0].element[27].target.equivalence = #equivalent
* group[0].element[27].target.code = #LVL
* group[0].element[27].target.display = "Left Vastus Lateralis"
* group[0].element[28].code = #NB
* group[0].element[28].display = "Nebulized"
* group[0].element[28].target.equivalence = #equivalent
* group[0].element[28].target.code = #NB
* group[0].element[28].target.display = "Nebulized"
* group[0].element[29].code = #PA
* group[0].element[29].display = "Perianal"
* group[0].element[29].target.equivalence = #equivalent
* group[0].element[29].target.code = #PA
* group[0].element[29].target.display = "Perianal"
* group[0].element[30].code = #PERIN
* group[0].element[30].display = "Perineal"
* group[0].element[30].target.equivalence = #equivalent
* group[0].element[30].target.code = #PERIN
* group[0].element[30].target.display = "Perineal"
* group[0].element[31].code = #RA
* group[0].element[31].display = "Right Arm"
* group[0].element[31].target.equivalence = #equivalent
* group[0].element[31].target.code = #RA
* group[0].element[31].target.display = "Right Arm"
* group[0].element[32].code = #RAC
* group[0].element[32].display = "Right Anterior Chest"
* group[0].element[32].target.equivalence = #equivalent
* group[0].element[32].target.code = #RAC
* group[0].element[32].target.display = "Right Anterior Chest"
* group[0].element[33].code = #RACF
* group[0].element[33].display = "Right Antecubital Fossa"
* group[0].element[33].target.equivalence = #equivalent
* group[0].element[33].target.code = #RACF
* group[0].element[33].target.display = "Right Antecubital Fossa"
* group[0].element[34].code = #RD
* group[0].element[34].display = "Right Deltoid"
* group[0].element[34].target.equivalence = #equivalent
* group[0].element[34].target.code = #RD
* group[0].element[34].target.display = "Right Deltoid"
* group[0].element[35].code = #RE
* group[0].element[35].display = "Right Ear"
* group[0].element[35].target.equivalence = #equivalent
* group[0].element[35].target.code = #RE
* group[0].element[35].target.display = "Right Ear"
* group[0].element[36].code = #REJ
* group[0].element[36].display = "Right External Jugular"
* group[0].element[36].target.equivalence = #equivalent
* group[0].element[36].target.code = #REJ
* group[0].element[36].target.display = "Right External Jugular"
* group[0].element[37].code = #OD
* group[0].element[37].display = "Right Eye"
* group[0].element[37].target.equivalence = #equivalent
* group[0].element[37].target.code = #OD
* group[0].element[37].target.display = "Right Eye"
* group[0].element[38].code = #RF
* group[0].element[38].display = "Right Foot"
* group[0].element[38].target.equivalence = #equivalent
* group[0].element[38].target.code = #RF
* group[0].element[38].target.display = "Right Foot"
* group[0].element[39].code = #RG
* group[0].element[39].display = "Right Gluteus Medius"
* group[0].element[39].target.equivalence = #equivalent
* group[0].element[39].target.code = #RG
* group[0].element[39].target.display = "Right Gluteus Medius"
* group[0].element[40].code = #RH
* group[0].element[40].display = "Right Hand"
* group[0].element[40].target.equivalence = #equivalent
* group[0].element[40].target.code = #RH
* group[0].element[40].target.display = "Right Hand"
* group[0].element[41].code = #RIJ
* group[0].element[41].display = "Right Internal Jugular"
* group[0].element[41].target.equivalence = #equivalent
* group[0].element[41].target.code = #RIJ
* group[0].element[41].target.display = "Right Internal Jugular"
* group[0].element[42].code = #RLAQ
* group[0].element[42].display = "Rt Lower Abd Quadrant"
* group[0].element[42].target.equivalence = #equivalent
* group[0].element[42].target.code = #RLAQ
* group[0].element[42].target.display = "Rt Lower Abd Quadrant"
* group[0].element[43].code = #RLFA
* group[0].element[43].display = "Right Lower Forearm"
* group[0].element[43].target.equivalence = #equivalent
* group[0].element[43].target.code = #RLFA
* group[0].element[43].target.display = "Right Lower Forearm"
* group[0].element[44].code = #RMFA
* group[0].element[44].display = "Right Mid Forearm"
* group[0].element[44].target.equivalence = #equivalent
* group[0].element[44].target.code = #RMFA
* group[0].element[44].target.display = "Right Mid Forearm"
* group[0].element[45].code = #RN
* group[0].element[45].display = "Right Naris"
* group[0].element[45].target.equivalence = #equivalent
* group[0].element[45].target.code = #RN
* group[0].element[45].target.display = "Right Naris"
* group[0].element[46].code = #RPC
* group[0].element[46].display = "Right Posterior Chest"
* group[0].element[46].target.equivalence = #equivalent
* group[0].element[46].target.code = #RPC
* group[0].element[46].target.display = "Right Posterior Chest"
* group[0].element[47].code = #RSC
* group[0].element[47].display = "Right Subclavian"
* group[0].element[47].target.equivalence = #equivalent
* group[0].element[47].target.code = #RSC
* group[0].element[47].target.display = "Right Subclavian"
* group[0].element[48].code = #RT
* group[0].element[48].display = "Right Thigh"
* group[0].element[48].target.equivalence = #equivalent
* group[0].element[48].target.code = #RT
* group[0].element[48].target.display = "Right Thigh"
* group[0].element[49].code = #RUA
* group[0].element[49].display = "Right Upper Arm"
* group[0].element[49].target.equivalence = #equivalent
* group[0].element[49].target.code = #RUA
* group[0].element[49].target.display = "Right Upper Arm"
* group[0].element[50].code = #RUAQ
* group[0].element[50].display = "Right Upper Abd Quadrant"
* group[0].element[50].target.equivalence = #equivalent
* group[0].element[50].target.code = #RUAQ
* group[0].element[50].target.display = "Right Upper Abd Quadrant"
* group[0].element[51].code = #RUFA
* group[0].element[51].display = "Right Upper Forearm"
* group[0].element[51].target.equivalence = #equivalent
* group[0].element[51].target.code = #RUFA
* group[0].element[51].target.display = "Right Upper Forearm"
* group[0].element[52].code = #RVL
* group[0].element[52].display = "Right Vastus Lateralis"
* group[0].element[52].target.equivalence = #equivalent
* group[0].element[52].target.code = #RVL
* group[0].element[52].target.display = "Right Vastus Lateralis"
* group[0].element[53].code = #RVG
* group[0].element[53].display = "Right Ventragluteal"
* group[0].element[53].target.equivalence = #equivalent
* group[0].element[53].target.code = #RVG
* group[0].element[53].target.display = "Right Ventragluteal"
