name: Download CSV Files
on:
  push:
    paths:
      - 'mappings/*.csv'
      - '.github/workflows/update-csvs.yaml'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout Files
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.5.3

      - name: Build the Conversion tools
        run: mvn compile package

      - name: Download files
        run: |
          del mappings\segments\*.csv mappings\messages\*.csv mappings\codesystems\*.csv mappings\datatypes\*.csv
          "%JAVA_HOME%\bin\java" -classpath target\v2-to-fhir.jar;target\lib\* org.hl7.v2tofhir.Convert -omappings/segments "-rmappings\v2-to-FHIR Map Inventory - Segment.csv" -omappings/datatypes "-rmappings\v2-to-FHIR Map Inventory - Data Type.csv" -omappings/messages "-rmappings\v2-to-FHIR Map Inventory - Message.csv" -omappings/codesystems "-dmappings\v2-to-FHIR Map Inventory - Code System.csv"

      - name: Recreate SUSHI Files
        run: |
          del input\Datatype*.fsh input\Segment*.fsh input\Table*.fsh input\Message*.fsh
          "%JAVA_HOME_11_X64%\bin\java" -cp target\v2-to-fhir.jar;target\lib\* org.hl7.v2tofhir.Convert -o. mappings/messages mappings/segments mappings/datatypes mappings/codesystems

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Add downloaded CSV files"

      - name: Push Changes to GitHub
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push
